### ISSUE TITLE
Elasticsearch on Secure Hadoop Cluster

### ISSUE THREAD

**Issue by ejwalk** [elastic/elasticsearch-hadoop#429] opened 2015-04-22 14:45 UTC
I'm working on running elasticsearch on yarn in a secured hadoop cluster (HDP 2.2). It is failing when instantiating the containers with the error below. The issue appears that the Kerberos based JAAS Principal is not being passed from the launching container to the child containers. This could be a configuration issue, it could also just be something that is not implemented in the elasticsearch on yarn module. Was hoping to get a quick clarification before I spend too much time troubleshooting.

The files are uploaded in HDFS:

```
[root@ldevawshdp0001 elasticsearch-yarn]# hadoop fs -ls /apps/elasticsearch
Found 2 items
-rw-r--r--   2 ewalk hdfs   31442427 2015-04-21 18:35 /apps/elasticsearch/elasticsearch-1.5.1.zip
-rw-r--r--   2 ewalk hdfs      53819 2015-04-21 18:35 /apps/elasticsearch/elasticsearch-yarn-2.1.0.BUILD-SNAPSHOT.jar
```

We are able to run other YARN jobs successfully, this is something specific to elastic's spin up process.

The issue occurs only when the containers that are launched to be the elastic cluster members try to access HDFS.

There are thousands of different applications that can run in YARN containers, many of them do not have this issue. For instance the Spark Hadoop RDD is able to successfully connect using this code:

https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/HadoopRDD.scala
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala

Essentially, when you start an application in YARN, the master has the credentials of the user that launched it by default, but the application containers out on the node managers will not have any credentials unless they are specifically delegated out to them by the code running on the master.

```
15/04/21 19:17:32 INFO am.ApplicationMaster: Starting ApplicationMaster...
15/04/21 19:17:32 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/04/21 19:17:32 INFO client.RMProxy: Connecting to ResourceManager at ldevawshdp0002.cedargatepartners.pvc/10.4.0.7:8030
15/04/21 19:17:33 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
15/04/21 19:17:33 INFO am.EsCluster: Allocating Elasticsearch cluster with 2 nodes
15/04/21 19:17:38 INFO impl.AMRMClientImpl: Received new token for : ldevawshdp0002.cedargatepartners.pvc:45454
15/04/21 19:17:38 INFO impl.AMRMClientImpl: Received new token for : ldevawshdp0001.cedargatepartners.pvc:45454
15/04/21 19:17:38 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/04/21 19:17:38 WARN ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
15/04/21 19:17:38 INFO am.EsCluster: Cluster has completed running...
15/04/21 19:17:53 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find Elasticsearch zip at [/apps/elasticsearch/elasticsearch-1.5.1.zip]; make sure the artifacts have been properly provisioned and the correct permissions are in place.
    at org.elasticsearch.hadoop.yarn.am.EsCluster.setupEsZipResource(EsCluster.java:224)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.launchContainer(EsCluster.java:191)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.start(EsCluster.java:115)
    at org.elasticsearch.hadoop.yarn.am.ApplicationMaster.run(ApplicationMaster.java:79)
    at org.elasticsearch.hadoop.yarn.am.ApplicationMaster.main(ApplicationMaster.java:104)
Caused by: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "ldevawshdp0002/10.4.0.7"; destination host is: "ldevawshdp0001.cedargatepartners.pvc":8020; 
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:772)
    at org.apache.hadoop.ipc.Client.call(Client.java:1472)
    at org.apache.hadoop.ipc.Client.call(Client.java:1399)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
    at com.sun.proxy.$Proxy17.getFileInfo(Unknown Source)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:752)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy18.getFileInfo(Unknown Source)
    at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1988)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1118)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1114)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1114)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.setupEsZipResource(EsCluster.java:222)
    ... 4 more
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
    at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:643)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:730)
    at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:368)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1521)
    at org.apache.hadoop.ipc.Client.call(Client.java:1438)
    ... 21 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
    at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:212)
    at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:413)
    at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:553)
    at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:368)
    at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:722)
    at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:717)
    ... 24 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
    at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
    at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:121)
    at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
    at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:223)
    at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
    at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
    at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:193)
    ... 33 more
```

**Comment by costin** [comment] 2015-06-09 19:28
_edited for your post to add minor formatting_

Apologies for the delayed response. Sorry to hear about your issues.
I think the reason this occurs is because in its current form, the YARN integration does not allow a Hadoop configuration to be passed in explicitly.  Well, it does pick one if it's available in the classpath but ideally one should be able to specify one or multiple and thus, any Hadoop configuration (such as Kerberos) to be loaded in.

I've pushed a minor fix that _might_ address your issue (please try the nightly builds); I've opened a new issue to expand the YARN configuration and allow Hadoop file(s) to be specified.

**Comment by ejwalk** [comment] 2015-06-09 20:24
Thanks Costin,

We've moved on to other options as of now, but if I get a chance to test this I will.

Best,
Eric

**Comment by trixpan** [comment] 2015-07-13 12:52
this seems to affect ElasticSearch for Yarn running on a Secure MapR clister.

Error is slightly different but seems to have a similar theme: *ticket*

```
Application application_1436527163771_0022 failed 2 times due to AM Container for appattempt_1436527163771_0022_000002 exited with exitCode: 255 due to: Exception from container-launch:
org.apache.hadoop.util.Shell$ExitCodeException:
at org.apache.hadoop.util.Shell.runCommand(Shell.java:505)
at org.apache.hadoop.util.Shell.run(Shell.java:418)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:295)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:314)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
main : command provided 1
main : user is trixpan
main : requested yarn user is trixpan
Can't open file /tmp/hadoop-mapr/nm-local-dir/nmPrivate/application_1436527163771_0022/ticketfile as node manager - No such file or directory failed to open external credential file /tmp/hadoop-mapr/nm-local-dir/nmPrivate/application_1436527163771_0022/ticketfile
Container exited with a non-zero exit code 255
.Failing this attempt.. Failing the application. 
```

Can you confirm the ES for Yarn works under secure clusters?

**Comment by costin** [comment] 2015-07-13 14:50
@trixpan Care to elaborate what your setup is? What version of MapR are you using and what are you trying to do? Ideally, this could be replicated using the MapR VM.
I mention this since it is unclear from the logs whether the user (trixpan) does not have the rights to access the ticket or whether the ticket file itself does not exist.

Thanks!

**Comment by trixpan** [comment] 2015-07-14 10:25
I tested this at lab, 3 VMs running M3 on 4.0.2 installed on top of Centos running in Secure mode but without Kerberos integration (i.e. Using MapR SASL tickets / "maprlogin password" command ) 

trixpan user is a valid unix user, as well to a user with admin privileges on MapR's MCS and is authenticated to cluster when submitting the job.

It seems to me the files is never created, hence the "No such file or directory". This seems to confirmed by a inotify rule created to monitor changes/access to /tmp/hadoop-mapr/nm-local-dir/nmPrivate/ in all the nodes. No signs of that file existing.

Also worth of mention, all my other jobs seems to work ok in terms of authentication.

**Comment by jbaiera** [comment] 2017-07-12 17:59
Closing this as the ES-on-YARN Beta is now deprecated and will be removed in 6.0

**Closed by jbaiera** 2017-07-12 17:59 UTC
Labels: :Yarn, bug, enhancement
