### ISSUE TITLE
URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " S"

### ISSUE THREAD

**Issue by anand-singh** [elastic/elasticsearch-hadoop#747] opened 2016-04-15 07:10 UTC
`"org.elasticsearch" % "elasticsearch-spark_2.11" % "2.3.0"`

```
[error] (run-main-0) java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " S"
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " S"
	at java.net.URLDecoder.decode(URLDecoder.java:194)
	at org.elasticsearch.hadoop.util.StringUtils.decodeQuery(StringUtils.java:404)
	at org.elasticsearch.hadoop.util.StringUtils.tokenizeAndUriDecode(StringUtils.java:135)
	at org.elasticsearch.hadoop.serialization.dto.mapping.MappingUtils.validateMapping(MappingUtils.java:45)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:271)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:61)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:60)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:27)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:190)
	at org.apache.spark.sql.execution.Limit.executeCollect(basicOperators.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectPublic(SparkPlan.scala:174)
	at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1499)
	at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$DataFrame$$execute$1$1.apply(DataFrame.scala:1499)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
	at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:2086)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$execute$1(DataFrame.scala:1498)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$collect(DataFrame.scala:1505)
	at org.apache.spark.sql.DataFrame$$anonfun$head$1.apply(DataFrame.scala:1375)
	at org.apache.spark.sql.DataFrame$$anonfun$head$1.apply(DataFrame.scala:1374)
	at org.apache.spark.sql.DataFrame.withCallback(DataFrame.scala:2099)
	at org.apache.spark.sql.DataFrame.head(DataFrame.scala:1374)
	at org.apache.spark.sql.DataFrame.take(DataFrame.scala:1456)
	at org.apache.spark.sql.DataFrame.showString(DataFrame.scala:170)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:350)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:311)
	at org.apache.spark.sql.DataFrame.show(DataFrame.scala:319)
	at com.rklick.engine.example.ESDataTest$.main(ESDataTest.scala:44)
	at com.rklick.engine.example.ESDataTest.main(ESDataTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by costin** [comment] 2016-04-15 07:14
Any code sample to reproduce this?

**Comment by anand-singh** [comment] 2016-04-15 08:27
Hi @costin,

Thanks for quick response.

##### Code Sample:
```scala
object ESDataTest {

  def main(args: Array[String]): Unit = {
    val conf = new SparkConf(false)
      .setMaster("local[*]")
      .set("es.nodes", ELASTIC_NODES)
      .set("es.port", ELASTIC_PORT)
      .setAppName("Text File Test")

    val sc: SparkContext = new SparkContext(conf)
    val ssc: SQLContext = new SQLContext(sc)

    val df = ssc.esDF("pharmadata/test")
    df.printSchema()
    df.show()
  }

}
```

Ingest below file into ES and try to read it using above code sample.
[PharmaData1.txt](https://github.com/elastic/elasticsearch-hadoop/files/220569/PharmaData1.txt)

Thanks,
Anand

**Comment by costin** [comment] 2016-05-02 13:58
Fixed in master and 2.x. The problem was caused by Spark infrastructure not URI escaping the field names which, when using special fields (like `%something`) caused the exception to occur.

**Closed by costin** 2016-05-02 13:58 UTC
Labels: 5.0.0-alpha2, bug, spark, v2.3.1
