### ISSUE TITLE
Cannot detect ES version in AWS Glue

### ISSUE THREAD

**Issue by nmtruong93** [elastic/elasticsearch-hadoop#2101] opened 2023-06-19 07:55 UTC
### What kind an issue is this?
I want to connect to ElasticSearch in AWS Glue, but it has an error as below.
It runs well in localhost but not in Glue. I already connect Glue to ElasticSearch VPC
Note: I'm not refer to use org.elasticsearch.spark.sql
```
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)
df = sqlContext.read.format("org.elasticsearch.spark.sql").load("index/type")
df.printSchema()
```

### Issue description

Description

### Steps to reproduce

Code:

```
 conf = {
            "es.nodes.wan.only": "true",
            "es.nodes": "nodes",
            "es.resource": index,
            "es.read.unmapped.fields.ignore": "false",
            "es.field.read.validate.presence": "warn",
            "es.read.field.include": field_include,
            "es.read.field.as.array.include": array_include,
            "es.read.field.as.array.exclude": array_exclude,
            "es.query": query,
            "pushdown": "true",
        }
        rdd = self.spark_context.newAPIHadoopRDD(
            inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
            keyClass="org.apache.hadoop.io.NullWritable",
            valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
            conf=conf
        )
df = rdd.map(lambda x: x[1]).toDF(schema=schema)
```

Strack trace:

```
An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD. Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
``` 

### Version Info
ES-Hadoop   :   elasticsearch-spark-30_2.12-8.8.1.jar
ES          :  7.13
Glue: 4.0

**Comment by jbaiera** [comment] 2023-06-21 17:32
Thanks for your interest in ES-Hadoop!

This error message is a generic error message that says that the library could not connect to the Elasticsearch nodes you have provided. This is often a connectivity problem brought on by either network visibility problems or because the client is missing some environment specific connection configurations (SSL, proxies, wan-mode, etc).

Without more logs from the process running ES-Hadoop there's not much we can go on to help out here. If you can add more information from the logs (preferably the exceptions logged before the final exception) we can see if we can troubleshoot further, but this issue is likely a configuration problem and not a bug. Until we can confirm it's a code problem, I'm going to close this issue out. We can reopen later if need be.

**Closed by jbaiera** 2023-06-21 17:32 UTC
