### ISSUE TITLE
TimestampWritableV2

### ISSUE THREAD

**Issue by mashuiping** [elastic/elasticsearch-hadoop#1297] opened 2019-05-30 08:42 UTC
### What kind an issue is this?
data mapping

### Issue description

mapping date filed from es with timestamp result the following errror:

Error: java.io.IOException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.hive.serde2.io.TimestampWritable cannot be cast to org.apache.hadoop.hive.serde2.io.TimestampWritableV2 (state=,code=0)

similary question: https://discuss.elastic.co/t/cannot-handle-type-timestampwritablev2-exception-when-creating-index-with-es-hadoop-connector/158220

### Version Info

OS:         : debian 9  
JVM         :   
Hive : Hive 3.1.0.3.1.0.0-78   
ES-Hadoop   :  7.0.1
ES          :  6.3.2

**Comment by jbaiera** [comment] 2019-06-18 14:50
ES-Hadoop does not support Hive 3.x yet. Closing as a duplicate of https://github.com/elastic/elasticsearch-hadoop/issues/744

**Closed by jbaiera** 2019-06-18 14:50 UTC
