### ISSUE TITLE
Casting SparkSQL - scala.collection.convert.Wrappers$JListWrapper is not a valid external type for schema

### ISSUE THREAD

**Issue by rafafrdz** [elastic/elasticsearch-hadoop#2043] opened 2022-11-22 11:37 UTC
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Hello,
I'd try reading data from an instance of elastic search via SparkSQL and it throw a casting exception.

The provided schema is the following:
```
root
 |-- categories: struct (nullable = true)
 |    |-- id: string (nullable = true)
 |    |-- name: string (nullable = true)
```

### Steps to reproduce

Code:

```scala
  val indice: String = "movies"

  lazy val customSparkOptions: Map[String, String] = Map(
    "es.nodes" -> "localhost",
    "es.net.http.auth.user" -> "elastic",
    "es.net.http.auth.pass" -> "admin",
    "es.resource" -> indice,
    "es.nodes.wan.only" -> "true",

  )
  lazy val sparkConf = new SparkConf().setAll(customSparkOptions)

  lazy val spark: SparkSession =
    SparkSession
      .builder()
      .master("local[2]")
      .config(sparkConf)
      .getOrCreate()

  val elasticDF: DataFrame = spark.read.format("org.elasticsearch.spark.sql").load(indice).select("categories")

  elasticDF.printSchema()
  elasticDF.show(false)
```

Strack trace:

```
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: scala.collection.convert.Wrappers$JListWrapper is not a valid external type for schema of struct<id:string,name:string>
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else named_struct(id, if (validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, categories), StructField(id,StringType,true), StructField(name,StringType,true)).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, categories), StructField(id,StringType,true), StructField(name,StringType,true)), 0, id), StringType), true, false), name, if (validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, categories), StructField(id,StringType,true), StructField(name,StringType,true)).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, categories), StructField(id,StringType,true), StructField(name,StringType,true)), 1, name), StringType), true, false)) AS categories#28
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:215)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:197)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: scala.collection.convert.Wrappers$JListWrapper is not a valid external type for schema of struct<id:string,name:string>
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.Invoke_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.CreateNamedStruct_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:211)
	... 19 more
``` 

### Version Info

OS:         :  ubuntu 20.04
JVM         :  1.8.0_342
Hadoop/Spark:  3.0.1
ES-Hadoop   :  7.12.0
ES          :  7.12.0
Scala      : 2.12.8

**Comment by masseyke** [comment] 2022-11-23 15:09
This seems to work fine on the `main` branch. I haven't tried yet on 7.12. Are you sure you're using the right es-spark jar? Which one are you using? Also, Hadoop and Spark are versioned independently -- do they both just happen to be at 3.0.1? This is probably a better discussion for https://discuss.elastic.co/.

**Comment by rafafrdz** [comment] 2022-11-25 08:19
What seems to happen is I have to explicitly define the field `categories` as an array field using `"es.read.field.as.array.include" -> "categories:2"` (Because it has deeper 2). While elastic search datasource cast `categories`'s elastic datatype (`text`) obtained from `flowers`'s mapping as `StringType`, `flowers` indice contains `"categories":[[{"id":"10.12","name":"Flower"}]]` as `categories` values, which is parsed by the parser as `Buffer[Buffer[...]]`

So, there is a discrepancy between the scala type that I obtain by the parser and the obtained spark type.

Unfortunately, this behavior is correct related to the Elastic documentation about how "array" type works:

> In Elasticsearch, arrays do not require a dedicated field data type. Any field can contain zero or more values by default, however, all values in the array must be of the same field type. See [Arrays](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/array.html).

* https://www.elastic.co/guide/en/elasticsearch/reference/7.10/mapping-types.html#types-array-handling
* https://www.elastic.co/guide/en/elasticsearch/reference/7.10/array.html

However, in my opinion, this is a semantic issue because you can map (or you can understand), for example, a simple type like `text` some of the following values: "value", ["value"], ["value", ["value2", "value3"]], etc. There is indeterminism.

**Comment by rafafrdz** [comment] 2022-11-25 08:24
Is there a workaround to get any metadata that indicates what field is an array or an array of array, etc before parsing values contained in the indice? I mean, to know what real type has the value (by looking for in the Elastic's metadatas) before it will be read.

**Comment by masseyke** [comment] 2023-03-08 20:31
Hi @rafafrdz. I'm sorry I dropped the ball on this one. I'm not sure I understand your post about reproducing it at https://github.com/elastic/elasticsearch-hadoop/issues/2043#issuecomment-1327145061. Here's a test I've added locally to [AbstractScalaEsScalaSparkSQL](https://github.com/elastic/elasticsearch-hadoop/blob/main/spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala), and this test passes. Can you tell me how to modify it to reproduce the failure you're seeing? You can run the test with `./gradlew :elasticsearch-spark-30:integrationTest --tests "org.elasticsearch.spark.integration.SparkSQLScalaSuite"` on the command line.
```
  @Test
  def testIssue2043() {
    val mapping = s"""{
                     |"dynamic":"strict",
                     |      "properties": {
                     |        "categories": {
                     |            "properties": {
                     |                    "id":{"type":"keyword","index":false},
                     |                    "name":{"type":"text","index":false}
                     |             }
                     |        }
                     |      }
                     |  }
    """.stripMargin
    val index = "test1"
    RestUtils.touch(index)
    RestUtils.putMapping(index, null, mapping.getBytes(StringUtils.UTF_8))
    val document = """{ "categories": {"id": "some_id", "name": "some_name" }}"""
      .stripMargin
    sc.makeRDD(Seq(document)).saveJsonToEs(index)
    RestUtils.refresh(index)
    val df = sqc.read.format("es").load(index)
    val cats = df.select("categories")
    assertThat(cats.first().get(0).asInstanceOf[Row].get(0).toString, equalTo("some_id"))
    assertThat(cats.first().get(0).asInstanceOf[Row].get(1).toString, equalTo("some_name"))
  }
```

**Comment by rafafrdz** [comment] 2023-03-11 23:19
That no respond my question. I will try to be more clear. If you have a mapping with indicate that a field is a `text` type for instance, but the real value for that field in that indice is an array of text values. You have to know before that field is an array and set explicitly "es.read.field.as.array.include" -> "field_name:1". This way elastic's datsource can cast it as an arraybuffer and map it to `ArrayType[StringType]` catalyst' type.

My question is: Is there any way to know automatically (without to know what values is in the field previously) if it is an array and then to cast it  as ArrayType after? I mean, by knowing any metadata from the indice's mapping or something like that? I think that probably not, because I think elasticsearch has no way to distinguish if their values are an array or not. But I wonder if you guys know anything.

Thank so much! :)

**Comment by masseyke** [comment] 2023-03-20 15:14
I'm not sure I completely understand your question, but I suspect that the answer is no because you are correct that Elasticsearch sees all fields are arrays.
And to modify my test based on what you said, I think it would look like this:
```
  @Test
  def testIssue2043() {
    val mapping = s"""{
                     |"dynamic":"strict",
                     |      "properties": {
                     |        "categories": {
                     |            "properties": {
                     |                    "id":{"type":"keyword","index":false},
                     |                    "name":{"type":"text","index":false}
                     |             }
                     |        }
                     |      }
                     |  }
    """.stripMargin
    val index = "test1"
    RestUtils.touch(index)
    RestUtils.putMapping(index, null, mapping.getBytes(StringUtils.UTF_8))
    val document = """{ "categories": {"id": "some_id", "name": ["some_name", "some_other_name"] }}"""
      .stripMargin
    sc.makeRDD(Seq(document)).saveJsonToEs(index)
    RestUtils.refresh(index)
    val df = sqc.read.format("es").load(index)
    val cats = df.select("categories")
    assertThat(cats.first().get(0).asInstanceOf[Row].get(0).toString, equalTo("some_id"))
    assertThat(cats.first().get(0).asInstanceOf[Row].get(1).toString, equalTo("some_name"))
  }
```
Is that correct? Doing that I get the same exception you originally reported:
```
java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: scala.collection.convert.Wrappers$JListWrapper is not a valid external type for schema of string
```
But as you point out, that is expected behavior because I did not specify `"es.read.field.as.array.include"`. So it sounds like we can close this out as expected (although unpleasant) behavior. Or we could potentially change this to a feature request to make the error message more useful -- the existing one is terrible.

**Closed** 2023-03-22 08:07 UTC
