### ISSUE TITLE
Installing Elasticsearch via YARN Fails

### ISSUE THREAD

**Issue by razaba** [elastic/elasticsearch-hadoop#886] opened 2016-11-02 17:09 UTC
### Issue description

Description
downloaded the latest distribution from elastic.co
while trying to install es 5 on my yarn cluster I received file not found 
### Steps to reproduce

Code:
```
wget http://download.elastic.co/hadoop/elasticsearch-hadoop-5.0.0.zip
unzip elasticsearch-hadoop-5.0.0.zip
cd elasticsearch-hadoop-5.0.0/dist/
yarn jar elasticsearch-yarn-5.0.0.jar -download-es
```

Strack trace:

```
Downloading Elasticsearch 5.0.0
Abnormal execution:java.io.IOException: Can't get https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.0.0.zip to ./downloads/elasticsearch-5.0.0.zip
java.lang.IllegalStateException: java.io.IOException: Can't get https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.0.0.zip to ./downloads/elasticsearch-5.0.0.zip
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.run(HttpDownloader.java:200)
Caused by: java.io.IOException: Can't get https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.0.0.zip to ./downloads/elasticsearch-5.0.0.zip
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.downloadFile(HttpDownloader.java:311)
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.get(HttpDownloader.java:212)
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.run(HttpDownloader.java:198)
Caused by: java.io.FileNotFoundException: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.0.0.zip
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.downloadFile(HttpDownloader.java:304)
        ... 2 more
Caused by: java.io.FileNotFoundException: https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-5.0.0.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.openConnection(HttpDownloader.java:258)
        at org.elasticsearch.hadoop.yarn.util.HttpDownloader$GetThread.get(HttpDownloader.java:206)
        ... 1 more

```

**Comment by jbaiera** [comment] 2016-11-02 20:48
I've linked the above issue as a more generalist solution path. 

In the mean time, as a work around, you could specify a config file with the `loadConfig` command line option which sets the `download.es.url` property to `https://artifacts.elastic.co/downloads/elasticsearch/`

There's more information on the `loadConfig` option in the [documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/ey-usage.html#yarn-options).

**Comment by jbaiera** [comment] 2017-07-12 18:01
Closing as duplicate of #887

**Closed by jbaiera** 2017-07-12 18:01 UTC
Labels: :Yarn, bug
