### ISSUE TITLE
stored_fields unable to fetch data

### ISSUE THREAD

**Issue by vishnugs** [elastic/elasticsearch-hadoop#1658] opened 2021-05-08 17:32 UTC
### Issue description

Unable to fetch data from elasticsearch spark when stored_fields=true in query 

### Steps to reproduce

Code:

```
String query = ?q=:*&stored_fields=:*";
JavaPairRDD<String, Map<String, Object>> testRdd = JavaEsSpark.esRDD(sc, "<index_name>",query);

```

Strack trace:

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1) (192.168.1.15 executor driver): org.apache.spark.util.TaskCompletionListenerException: Unknown stored_fields parameter; please change the URI query into a Query DLS (see 'Query String Query')

Previous exception in task: Unknown stored_fields parameter; please change the URI query into a Query DLS (see 'Query String Query')
	org.elasticsearch.hadoop.rest.query.SimpleQueryParser.applyURIParameter(SimpleQueryParser.java:90)
	org.elasticsearch.hadoop.rest.query.SimpleQueryParser.parseURI(SimpleQueryParser.java:66)
	org.elasticsearch.hadoop.rest.query.SimpleQueryParser.parse(SimpleQueryParser.java:49)
	org.elasticsearch.hadoop.rest.query.QueryUtils.parseQuery(QueryUtils.java:57)
	org.elasticsearch.hadoop.rest.RestService.createReader(RestService.java:449)
	org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader$lzycompute(AbstractEsRDDIterator.scala:49)
	org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader(AbstractEsRDDIterator.scala:42)
	org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31``` 

```
### Version Info
 
OS:         :       Ubuntu
JVM         :       8 
Hadoop/Spark:   Spark 3.1.1
ES-Hadoop   :  7.8.0
ES          :   7.8.0

```
<groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark20_2.12</artifactId>
            <version>7.8.0</version>

```

How to use stored_fields when using spark elasticsearch hadoop library ?

**Comment by jbaiera** [comment] 2021-05-10 19:37
This looks like a duplicate of issue #844 - Please feel free to +1 that issue. Closing this as duplicate.

**Closed by jbaiera** 2021-05-10 19:37 UTC
