### ISSUE TITLE
409 is not always unrecoverable

### ISSUE THREAD

**Issue by AlexeyRaga** [elastic/elasticsearch-hadoop#613] opened 2015-11-19 06:00 UTC
Since `elasticsearch-hadoop` provides the ability to set up the external version (`es.mapping.version`) it would be nice to have a bit more control on it.

The problem is that when executing a batch that contains a version conflict the job fails with 

```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Conflict(409) - Bailing out...
```

In some of the situations (typical dedup) it is perfectly fine to accept the fact that there could be older versions and to just ignore them.

The ES itself supports this feature: it returns status `409` for conflicting documents and `201` for the rest of the documents:

Request:

```
POST /_bulk
{ "create": { "_index": "website", "_type": "blog", "_id": "123", "_version": 10, "version_type": "external" }}
{ "title":    "My first blog post" }
{ "create": { "_index": "website", "_type": "blog", "_id": "ccc" }}
{ "title":    "My ALWAYS post" }
```

Response:

```
{
  "took": 2,
  "errors": true,
  "items": [
    {
      "create": {
        "_index": "website",
        "_type": "blog",
        "_id": "123",
        "status": 409,
        "error": {
          "type": "version_conflict_engine_exception",
          "reason": "[blog][123]: version conflict, current [10], provided [10]",
          "shard": "0",
          "index": "website"
        }
      }
    },
    {
      "create": {
        "_index": "website",
        "_type": "blog",
        "_id": "ccc",
        "_version": 1,
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "status": 201
      }
    }
  ]
}  
```

It would be great if we have the ability to have a bit more control over the conflicting situations. It should at least be possible to instruct the spark driver to not fail on `409` version conflicts.

**Comment by mvervuurt** [comment] 2015-12-21 11:04
We also have this issue, having a configuration parameter than helps ignore version conflicts with the ES-Hadoop connector especially when using external versioning would be of grate value.

**Comment by jbaiera** [comment] 2017-03-28 18:20
Closing this as it is a duplicate of #307

**Closed by jbaiera** 2017-03-28 18:20 UTC
