### ISSUE TITLE
Issue connecting to ES Found

### ISSUE THREAD

**Issue by driadi** [elastic/elasticsearch-hadoop#703] opened 2016-02-20 11:03 UTC
I am trying to integrate ES Found and Hadoop with this Hive create table definition below: 
```
CREATE EXTERNAL TABLE es_event ( ... )
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'test',
'es.index.auto.create' = 'true',
'es.nodes' = 'found-host:9200';
```

However I am always getting `EsHadoopInvalidRequest: null` every time I attempt to connect to the ES cluster and get the data. Looking closer to the code itself, it seems that the error is caused by **404 Not Found** response when the library attempts to hit the ES API oddly by using the IP address instead of the provided host name?

Manually hitting the same address (ie. x.x.x.x:9200) on the browser returns with the error like:
`{"ok":false,"message":"Unknown cluster."}`

which I expected to return this instead:
```
{
  "status" : 200,
  "name" : "instance-0000000000",
  "cluster_name" : "xxx",
  "version" : {
    "number" : "1.7.5",
    "build_hash" : "xxx",
    "build_timestamp" : "2016-02-02T09:55:30Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

Any idea what causes this issue? Perhaps there is a setting that I missed?

Thanks for the support.

**Comment by dennyriadi** [comment] 2016-02-21 21:28
Found the cause of this issue. Apparently there is a method `SettingsUtils.resolveHostToIpIfNecessary()` that transforms the provided host URL as ip address. This remote ip is then used by the lib to make http request to the remote cluster.

Making http request to Found using this ip address AND without the host header returns 404.

Can you explain why this logic is required?

**Comment by mattk42** [comment] 2016-04-04 18:35
I am sure the issue is that on the Found side they use a single routing layer that routers for multiple clusters. They use the cluster id that would be in the host header to route to the correct elasticsearch instances themselves. 

If the client needs to do the lookup, I think adding the Host header would fix this I believe. 

Anyone find another way in the meantime?

**Comment by costin** [comment] 2016-04-06 17:25
The issue of resolving the hostname to IPs has been fixed in master - if not set it will default to true (convert) for non-wan scenarios, false otherwise.
I've just ran another test against Found/Cloud without any issues. Can you please try the [dev](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) build?

**Comment by dennyriadi** [comment] 2016-04-07 22:17
Thanks @costin, just tried the new dev build and I can confirm that it is now working. Cheers.

**Comment by costin** [comment] 2016-04-08 08:19
@dennyriadi Thanks for reporting and sorry for the inconvenience.

Cheers,

**Closed by costin** 2016-04-08 08:19 UTC
Labels: hive, spark, v2.2.1, v2.3.0-m1
