### ISSUE TITLE
Spark SQL 1.3 support - esDF function incorrectly maps column names

### ISSUE THREAD

**Issue by fdmitriy** [elastic/elasticsearch-hadoop#451] opened 2015-05-14 15:03 UTC
Hi,

Environment:
Spark 1.3.0
elasticsearch 1.4.4
elasticsearch-hadoop 2.1.0.Beta4

When using esDF function to load data from Elasticsearch into Spark, columns get assigned to incorrect column names in the resulted DataFrame. The columns names that get assigned, they do exist in the index/type, but the mapping between the columns and column names is totally incorrect.

This bug doesn't happen when using the general Spark SQL 1.3 "load" function, columns are mapped to correct column names, but when using the load function instead of esDF and then doing JOIN with DataFrame loaded from Oracle, an exception happens (see issue #449: https://github.com/elastic/elasticsearch-hadoop/issues/449).

**Comment by jmahonin** [comment] 2015-05-26 19:43
I ran into this same issue myself using 2.1.0-Beta4. It seems to be resolved in the master branch, possibly by this commit:
https://github.com/elastic/elasticsearch-hadoop/commit/279e8938bc1f64d1b175d56dd17aaa488eb3fa4c

It's been some time, and a number of changes since the Beta4 release. A Beta5 (or full) 2.1.0 release would be great!

**Comment by costin** [comment] 2015-06-03 18:35
@fdmitriy @jmahonin Indeed, it has. Can you please try out the [snapshot/dev build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) and report back?

Thanks,

**Comment by costin** [comment] 2015-06-03 18:36
Duplicate of #441

**Closed** 2015-06-08 18:04 UTC
Labels: duplicate, spark
