### ISSUE TITLE
Query executes using Kibana but fails when queried via EsHadoop

### ISSUE THREAD

**Issue by PowerToThePeople111** [elastic/elasticsearch-hadoop#1127] opened 2018-03-28 15:45 UTC
### What kind an issue is this?

- [ x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
A query using a script to filter documents executes successfully when executed via Kibana, but will throw an exception when executed via spark-elasticsearch.
### Steps to reproduce

Code:

```
import ...

def queryElasticDF(url: String, ports: String, query: String, index: String) = {

      val spark = SparkSession.builder().getOrCreate()


      val sqlc = spark.sqlContext
      import sqlc.implicits._
      import org.elasticsearch.spark.sql._

      val cfg = Set(
        ("es.nodes",  url),
        ("es.port", ports),
        ("pushdown", "true"),
        ("es.read.metadata", "true"),
        ("es.read.metadata.field", "meta")
      ).toMap

      val result = spark.sqlContext.esDF(index, query, cfg)

      result
    }

val query = """
{
  "query": {
    "bool": {
      "must": [
        {
          "script": {
            "script": {
              "inline": "doc[\"mobile_id\"].value.length() > 35",
              "lang": "groovy"
            }
          }
        },
        {
          "term": {
            "platform": "ios"
          }
        }
      ]
    }
  }
}
"""
val result =queryElasticDF("some_url", "some_port",query, s"""some_index/click_event""")

result.write.mode(SaveMode.Overwrite).parquet(someLocationInHdfs)
```

Strack trace:

```
Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1958)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:127)
  ... 155 more
Caused by: org.apache.spark.SparkException: Task failed while writing rows
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:204)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
  ... 3 more
Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: error evaluating doc["mobile_id"].value.length() > 35
  at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:505)
  at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:463)
  at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:445)
  at org.elasticsearch.hadoop.rest.RestClient.scroll(RestClient.java:520)
  at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:377)
  at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:112)
  at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
  at scala.collection.Iterator$$anon$

``` 

### Version Info

OS:         :  Linux
JVM         :  
Hadoop/Spark:  Spark 2.1.1
ES-Hadoop   :  5.6.8
ES          :  5.6.8

**Comment by jbaiera** [comment] 2018-03-28 15:50
Could you provide some test data and a mapping that reproduces the above error? Also, since it's an invalid request exception, could you check if there is anything of importance in the Elasticsearch logs?

**Comment by PowerToThePeople111** [comment] 2018-03-29 08:41
Sorry, it would take a really long time to first find the actual subset of documents that produce the error and then I would have to anonymize them - potentially destroying the conditions that created the error. 

I played around more and could fix the issue by changing ...
```
"script": {
              "inline": "doc[\"mobile_id\"].value.length() > 35",
              "lang": "groovy"
            }
```

to

```
"script": {
              "source": "doc[\"mobile_id\"].value?.length() == 36,
              "lang": "painless"
            }
```
the thing which actually made the query work was to change the condition from `> 35` to `== 36`. why that is the case, i do not understand tho.
also i changed some other things which seem to be more in line with the syntax intended to use in our version (inline -> source and groovy -> painless) and also uses the null save operator "?" which seems to me like a good practice to use in filter conditions. 

Thanks for you help tho!

**Comment by PowerToThePeople111** [comment] 2018-03-29 08:59
I got a copy of the stacktrace from a colleague with access to the logs. I give it to you. Maybe it helps you or others like me in the same situation to identify a potential issue. I am unsure if everything is in the correct order... i somehow doubt it looking at the timestamps, but thats at least all i got for now:
```

[2018-03-29T08:01:07,577][WARN ][r.suppressed             ] path: /_search/scroll, params: {scroll=5m}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
		at org.elasticsearch.action.search.SearchScrollAsyncAction.onShardFailure(SearchScrollAsyncAction.java:269) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.action.search.SearchScrollAsyncAction$1.onFailure(SearchScrollAsyncAction.java:202) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1077) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1181) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1159) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:665) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:659) [elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.6.8.jar:5.6.8]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: org.elasticsearch.transport.RemoteTransportException: [ip-10-0-0-96][10.0.0.96:9300][indices:data/read/search[phase/query+fetch/scroll]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
		at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:447) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:114) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:393) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.action.search.SearchTransportService$10.messageReceived(SearchTransportService.java:387) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.action.search.SearchTransportService$10.messageReceived(SearchTransportService.java:384) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.8.jar:5.6.8]
		... 3 more
Caused by: org.elasticsearch.script.ScriptException: runtime error
		at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:101) ~[?:?]
		at org.elasticsearch.painless.PainlessScript$Script.execute(doc['mobile_id'].value.length() > 35:1) ~[?:?]
		at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:133) ~[?:?]
		at org.elasticsearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.get(ScriptQueryBuilder.java:186) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.apache.lucene.search.RandomAccessWeight$1.matches(RandomAccessWeight.java:63) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.ConjunctionDISI$ConjunctionTwoPhaseIterator.matches(ConjunctionDISI.java:345) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:253) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:197) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache.cacheIntoBitSet(LRUQueryCache.java:513) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache.cacheImpl(LRUQueryCache.java:504) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.cache(LRUQueryCache.java:708) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(LRUQueryCache.java:743) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.scorerSupplier(IndicesQueryCache.java:162) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.apache.lucene.search.BooleanWeight.scorerSupplier(BooleanWeight.java:400) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:381) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.Weight.bulkScorer(Weight.java:160) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:375) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.cache(LRUQueryCache.java:704) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(LRUQueryCache.java:743) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.scorerSupplier(IndicesQueryCache.java:162) ~[elasticsearch-5.6.8.jar:5.6.8]
		at org.apache.lucene.search.BooleanWeight.scorerSupplier(BooleanWeight.java:400) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
		at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:381) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
```

**Comment by jbaiera** [comment] 2018-04-26 19:16
Could you include the full query that you are using and the job configuration? Based on those Elasticsearch logs it looks like for some reason the cluster is treating the script as a painless script instead of groovy.

**Comment by jbaiera** [comment] 2018-06-22 17:00
Closing this as there have been no further responses. If any new information becomes available, this can be reopened.

**Closed by jbaiera** 2018-06-22 17:00 UTC
Labels: :Rest, feedback-requested
