### ISSUE TITLE
Issue in connecting hive with elasticsearch

### ISSUE THREAD

**Issue by Anish841** [elastic/elasticsearch-hadoop#701] opened 2016-02-17 11:05 UTC
I am trying  to pull data from elasticsearch to hive .I did configuration in hive classpath using:
bin/hive -hiveconf hive.aux.jars.path=/users/mjuttuba/elasticsearch-hadoop-2.1.0.jar

Elasticsearch data json:
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "testindex",
        "_type": "test",
        "_id": "1",
        "_score": 1,
        "_source": {
          "field1": "value1"
        }
      }
    ]
  }
}

i am using following to create external table on hive:
CREATE EXTERNAL TABLE testserver1 (
field1 STRING
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'testindex/test','es.nodes'='http://173.36.45.170',
'es.port' = '9200',
'es.index.auto.create' = 'false')

When i hit 
desc testserver1;
i am successfully  getting schema description.

But I am getting following error when i hit select query:
select * from testserver1;

Error:
Failed with exception java.io.IOException:org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[http://173.36.45.170]]

Need somebody help in the community.

**Comment by costin** [comment] 2016-02-18 01:43
Please use the [forum](http://discuss.elastic.co) not the issue tracker for
questions.

The error is likely caused by the hive server not having access to the
actual ES nodes.

**Comment by costin** [comment] 2016-04-08 13:57
As mentioned before - for questions, please use the dedicated [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) not the issue tracker.

Closing the issue.

**Closed by costin** 2016-04-08 13:57 UTC
Labels: hive, question, v2.2.1, v2.3.0-m1
