### ISSUE TITLE
"Cannot find node with id" exception even when the node is alive and cluster is green.

### ISSUE THREAD

**Issue by skkolli** [elastic/elasticsearch-hadoop#243] opened 2014-08-12 23:15 UTC
I am getting the following exception when pushing data from hadoop M/R job. When this happens, the node in question is responding and cluster is also healthy (green). Also, plenty of resources on the box. CPU usage is less than 30%, free memory is over 50G. With this exception, the hadoop map task is failing and getting restarted and eventually succeeding (may be by connecting to a different ES node). These errors are not consistent. They are very intermittent.

``` java
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id [Q4pQkOIJSSi2oXRXGUVs8w]
    at org.elasticsearch.hadoop.util.Assert.notNull(Assert.java:40)
    at org.elasticsearch.hadoop.rest.RestRepository.getWriteTargetPrimaryShards(RestRepository.java:251)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.initSingleIndex(EsOutputFormat.java:218)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:201)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:159)
    at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:638)
    at org.apache.hadoop.mapreduce.TaskInputOutputContext.write(TaskInputOutputContext.java:80)
    at afi.search.hadoop.es.ESMapper1.map(ESMapper1.java:227)
    at afi.search.hadoop.es.ESMapper1.map(ESMapper1.java:1)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:364)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
```

**Comment by sagarnarla** [comment] 2015-01-05 22:06
I am facing the same issue:
`org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id [_o_KDZezTde5wvYTpDQ8TA]`
when writing to ES from a MR job. 

However looking at my cluster none of the nodes have the ID (`_o_KDZezTde5wvYTpDQ8TA`) from the excpetion.

What seems to be the issue?

**Comment by costin** [comment] 2015-01-06 14:52
Can you check whether your cluster configuration has changed? Potentially a node briefly joined the cluster before going away? Is the error persistent? If so can you please provide some stats about your cluster such as version, number of nodes by either pointing your browser or `curl -XGET` to your cluster at
`/_nodes?pretty` and `/_search_shards?pretty` addresses and then pasting the output here or in a gist.
Thanks

**Comment by costin** [comment] 2015-01-06 14:53
@sagarnarla ^^

**Comment by costin** [comment] 2015-01-06 16:36
@agarwalsuchin @searchwizard @sagarnarla I've pushed another fix for this. Basically in case the state is inconsistent (the shards are backed by nodes that do not exist), es-hadoop will retry the 'discovery' process to get a more accurate picture. It will do so 3 times before giving up. For each failure, a warning will be logged with the shards vs nodes state.
I've pushed some artifacts for this - can you please try them out and report back?

Thanks!

**Comment by sagarnarla** [comment] 2015-01-06 18:21
The cluster configuration has not been changed. But there is a possibility one or more nodes might have restarted. Will the node ID change in that case?

_search_shards: https://gist.github.com/sagarnarla/3a675c002f56a88573cc#file-_search_shards
_nodes: https://gist.github.com/sagarnarla/3a675c002f56a88573cc#file-_nodes

**Comment by costin** [comment] 2015-01-06 18:36
Yes, the node ID is likely to change. This is basically a 'hiccup' - when a node goes away and the cluster transitions to the new state, at least that's is what I assume happens here considering I can't find the node id you mentioned which suggests a node left, a new one took its place and the data rebalanced).
The fix in master tries to cope with this by retrying the discovery and providing a more useful log warning - hopefully correlated with some cluster monitoring (like Marvel) and some stats the culprit becomes more obvious.

**Comment by vishalrp** [comment] 2015-02-03 07:31
I am experiencing this bug too. Using Spark, when I try 200 workers the job fails, however at 100 workers it runs fine. Also, I checked the http://localhost:9200/_search_shards?pretty and the nodes ID it complains about actually exist even after the failure. So I not sure if this is caused by a change in node ID. I'm using the 2.1.0.Beta3 release.

**Comment by agarwalsuchin** [comment] 2015-02-04 20:46
Currently, I am using elasticsearch-hadoop-2.1.0.BUILD-20150127.023409-265.jar. Since the error is transient in nature, I have not seen it yet. 
Costin, can I test this manually ? Will the following hack work ?

Because I am running my cluster on EC2, this is what I am planning to do to test this:
1. I am going to spin up an EC2 cluster with 21 nodes (1 Master and 20 Data nodes) with 10 shards and a replica for each shard.
2. During the indexing of my data, I am going to manually terminate one of the hosts that has a primary shard on it and then see the resultant behavior

Does this sound reasonble ?

**Comment by agarwalsuchin** [comment] 2015-03-23 17:13
Update:
I believe these two settings fixed this intermittent issue for me.
discovery.ec2.ping_timeout: 30s
discovery.zen.ping.multicast.enabled: false

Hypothesis:
I carefully monitored the behavior of the cluster and its nodes. It is not due to the cluster being in unstable (nodes getting dropped and added), but rather due to the networking delays Under heavy load, the nodes in the cluster do not respond in time to the pings. 

After increasing the ping timeouts, I have not seen this for almost > 20 runs. My typical run is starting an EMR cluster, installing Elasticsearch through a bootstrap action, indexing data, runing some queries and then taking a snapshot in S3. I always encoutered the error in indexing phase during which the cluster was under heavy load and some nodes may have missed the ping timeout window.

**Comment by searchwizard** [comment] 2015-03-23 22:27
I am not sure if the settings helped! When I originally reported the issue, my settings are same as you reported.

**Comment by costin** [comment] 2015-04-28 14:50
@agarwalsuchin @searchwizard Can you guy try the latest Beta (4) and report back whether it fixes the issue or not?
Thanks!

**Comment by ligyxy** [comment] 2015-05-21 15:18
I was facing the same issue, that it returns org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id 
while the node id is valid with es-hadoop 2.0.2

However, with Beta(4), it returns 
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [_nodes/transport] failed; server[null] returned [401|Unauthorized:]
with the same conf.

**Comment by jbaiera** [comment] 2017-06-07 20:03
Closing this issue as it seems that the conversation has trailed off.

**Closed by jbaiera** 2017-06-07 20:03 UTC
Labels: :Rest, bug
