### ISSUE TITLE
ISO8601 dates with timezone offset considered invalid on SQL FILTER CLAUSE

### ISSUE THREAD

**Issue by pkadetiloye** [elastic/elasticsearch-hadoop#495] opened 2015-07-07 00:54 UTC
This problem still exists when trying to execute a Spark SQL query on Elasticsearch with filter clause i.e `WHERE` or `GROUP BY`.
SQL query without the filters works and handles the date pretty well.

````
.204): java.lang.IllegalArgumentException: 2015-03-02T06:05
        at org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl$Parser.read(
Unknown Source)
        at org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl$Parser.skip(
Unknown Source)
        at org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl$Parser.parse
(Unknown Source)
        at org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl.<init>(Unkno
wn Source)
        at org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl.newXMLGregorianCa
lendar(Unknown Source)
        at javax.xml.bind.DatatypeConverterImpl._parseDateTime(DatatypeConverter
Impl.java:422)
        at javax.xml.bind.DatatypeConverterImpl.parseDateTime(DatatypeConverterI
mpl.java:417)
````

**Comment by costin** [comment] 2015-07-14 04:49
@pkadetiloye Can you please post a quick snippet (gist if it's a long one) of the relevant Spark SQL and associated sample data in Spark/Elastic?
The date above fails since it doesn't specify the timezone..

**Comment by pkadetiloye** [comment] 2015-07-16 16:06
@costin you are right, I finally figured out the field causing the error in my document.

Am wondering, this is still a valid date `2015-03-02T06:05`, should this even throw an exception ?

**Comment by costin** [comment] 2015-07-16 20:18
I need to run some tests to see how Joda/java.time/Elasticsearch interpret this date. Since the parsing is done using the JDK alone, we don't use Joda so this might be a corner case. I would argue that without a timezone, it is invalid (unless the spec mandates it will fallback to UTC but afaik, even that needs to be specified accordingly).

Btw, what Java version are you using?

**Comment by pkadetiloye** [comment] 2015-07-16 20:39
Since this type of date is already supported in Elasticsearch, It also makes sense to support it here.
As you said, running some test to see how Joda/java.time/Elasticsearch interprete this date will 
help.

For the spec, I checked `DatatypeConverter.parseDateTime(value)`  documentation, it expects
a valid `lexicalXSDDate` otherwise, it throws the exception above.

In DateUtils.java,
````
 public static Calendar parseDateJdk(String value) {
        // check for colon in the time offset
        int timeZoneIndex = value.indexOf("T");
        if (timeZoneIndex > 0) {
            int sign = value.indexOf("+", timeZoneIndex);
            if (sign < 0) {
                sign = value.indexOf("-", timeZoneIndex);
            }

            // +4 means it's either hh:mm or hhmm
            if (sign > 0) {
                // +3 points to either : or m
                int colonIndex = sign + 3;
                // +hh - need to add :mm
                if (colonIndex >= value.length()) {
                    value = value + ":00";
                }
                else if (value.charAt(colonIndex) != ':') {
                    value = value.substring(0, colonIndex) + ":" + value.substring(colonIndex);
                }
            }
        }

        return DatatypeConverter.parseDateTime(value);
    }

````

**Comment by costin** [comment] 2015-07-28 14:53
After spending significant time with this, the only reliable answer is using joda time. I'm working on detecting the "time" libraries available at runtime and if Joda is present, it will be used instead of the JDK function to parse the date.
With the introduction of `java.time` in Java 8 I was excited to support it however it seems to have a significant drawback as oppose to Joda and that is, it does not support chaining multiple `DateFormatters` which means it is not possible to support multiple year or time formats for example as Joda dateOptionalTime supports.
This is quite a shame since it would have simplified the requirements quite a lot as a lot more folks are running on Java 8 instead of having Joda around.

I'll ping you once the implementation hits master so you can try it out.

P.S. This example is a good one on the tricky bits of ISO8601 - a lot of components are made optional hence why the date above fails and where Joda adds a lot of value.

**Comment by pkadetiloye** [comment] 2015-07-28 18:21
@costin I completely agree. :+1: 

My work around was to completely re-index my data in Elasticsearch and ensure all my date is formatted correctly.

**Comment by costin** [comment] 2015-07-29 19:45
In master and 2.x, the parsing has been enhanced so that, if Joda library is detected, it is used instead for parsing dates which should alleviate this problem. The JDK 8 functionality is not there but hopefully it will be added in the future; it is confirmed the `dateOptionalTime` is not easy to implement so it will require some additional checks.

**Comment by costin** [comment] 2015-07-29 19:46
As a follow-up to the JDK 8 implementation, please see #508 
Closing the issue..

**Closed by costin** 2015-07-29 19:46 UTC
Labels: bug, spark, v2.1.1, v2.2.0.m1
