### ISSUE TITLE
the size parameter is always 0 when querying ElasticSearch from spark

### ISSUE THREAD

**Issue by cereusxing** [elastic/elasticsearch-hadoop#962] opened 2017-04-24 07:43 UTC
### What kind an issue is this?
I'm trying to query elasticsearch with the elasticsearch-hadoop connector(5.3.0) but nothing returned

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
Content can be fetched by accessing the url "/global/target/_search" via browser. How to remove the size parameter in spark? I tried "es.batch.size.entries", "es.scroll.size" and "es.scroll.limit", but still not working.

### Steps to reproduce

Code:
JavaRDD<String> esJsonRDD = JavaEsSpark.esJsonRDD(javaSparkContext, "global/target").values();

```
Test/code snippet
```

Strack trace:

According the debug log, the size is set as 0.

17/04/21 14:58:31 DEBUG header: >> "GET /global/target/_search?size=0&preference=_shards:0 HTTP/1.1[\r][\n]"
```
Stack trace goes here
``` 

### Version Info

OS:         :  CentOs6
JVM         :  1.7.0_80
Hadoop/Spark:  spark-2.1.0-bin-hadoop2.7
ES-Hadoop   :  5.3.0
ES          :  5.3.0

**Comment by jbaiera** [comment] 2017-04-24 14:37
@cereusxing Could you link your settings that you are using in your spark context? I'll work on trying to get a reproduction of this.

**Comment by cereusxing** [comment] 2017-04-26 08:07
es.batch.size.entries=20
es.http.timeout=2m
es.index.auto.create=true
es.nodes=10.110.9.181
es.nodes.discovery=false
es.nodes.wan.only=false
es.port=9200
es.resource=global/target
es.scroll.limit=100
es.scroll.size=60
spark.app.id=application_1490948832657_0302
spark.app.name=Spark-ElasticsSearch Integration
spark.driver.appUIAddress=http://10.110.9.180:4040
spark.driver.extraClassPath=/home/cereus/data/spark/lib/*
spark.driver.host=10.110.9.180
spark.driver.memory=1G
spark.driver.port=54923
spark.executor.extraClassPath=/home/cereus/data/spark/lib/*
spark.executor.id=driver
spark.executor.memory=1g
spark.jars=file:/home/cereus/software/test/SparkExample-1.0.jar
spark.master=yarn
spark.org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.param.PROXY_HOSTS=node01
spark.org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.param.PROXY_URI_BASES=http://node01:8088/proxy/application_1490948832657_0302
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.submit.deployMode=client
spark.ui.filters=org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter

**Comment by jbaiera** [comment] 2017-05-03 15:16
@cereusxing I'm not having any luck reproducing this locally. How do you have your logging set up that it retrieved that request line at `DEBUG` level? ES-Hadoop only logs that line in CommonsHttpTransport at `TRACE` level. Is it possible that you have some other client that is not pulling things correctly?

**Comment by jbaiera** [comment] 2017-07-24 18:11
Closing this out since there has been no further activity.

**Closed by jbaiera** 2017-07-24 18:11 UTC
Labels: :Spark, feedback
