### ISSUE TITLE
How to start spark-shell with elasticsearch-spark

### ISSUE THREAD

**Issue by coregear** [elastic/elasticsearch-hadoop#718] opened 2016-03-11 15:38 UTC
I find everywhere on internet but still can't run spark 1.6 with elasticsearch-spark 2.1.3
there is alway show this error, what ever how I load the elasticsearch-spark_2.11-2.1.3.jar

Please Please write more specify in docs. It's very hard to start, too I can't find where to start.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream

**Comment by costin** [comment] 2016-03-21 17:02
I'm sorry you are having issues. However from your bug report, I can't understand what the issue is. The class you are referring to (hadoop) does not belong to ES-Hadoop. 
Have you managed to run the spark shell by itself? It sounds like you are using the wrong distribution.

P.S. Speaking of docs, you might want to try the troubleshooting [page](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help).

**Comment by costin** [comment] 2016-04-08 13:55
Since there hasn't been any update on this issue, I'm closing it down. If the issue still persists, please open a new one (and potentially link this as well).

Cheers

**Closed by costin** 2016-04-08 13:55 UTC
Labels: question, spark, v2.2.1, v2.3.0-m1
