### ISSUE TITLE
Serialization Issue from scala.collection.immutable.HashMap$HashTrieMap

### ISSUE THREAD

**Issue by jfelectron** [elastic/elasticsearch-hadoop#369] opened 2015-02-01 20:23 UTC
Not sure if this should be implicitly handled or if I need to cast here:
```
15/02/01 12:20:26 WARN TaskSetManager: Lost task 6.0 in stage 0.0 (TID 6, localhost): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Cannot handle type [class scala.collection.immutable.HashMap$HashTrieMap], instance [Map(start_date -> 1980-06-01T00:00:00.000-07:00, industry -> Hospital & Health Care, id -> e143417d9770dc66205ff242863d9ae5, skills -> [ "ACLS" , "Acute Care" , "BLS" , "Case Managment" , "Clinical Research" , "Cpr Certified" , "Critical Care" , "Disease Management" , "EHR" , "EMR" , "Elder Care" , "HIPAA" , "Health Education" , "Healthcare" , "Healthcare Consulting" , "Healthcare Industry" , "Healthcare Information Technology" , "Healthcare Management" , "Home Care" , "Hospitals" , "ICU" , "Inpatient" , "JCAHO" , "Long-term Care" , "Managed Care" , "Medicaid" , "Medical Records" , "Medical Terminology" , "Medical/Surgical" , "Medicare" , "Medicine" , "Meditech" , "Mental Health" , "Nursing" , "Nursing Education" , "Orthopedic" , "Patient Advocacy" , "Patient Education" , "Patient Safety" , "Pediatrics" , "Physician Relations" , "Physicians" , "Quality Improvement" , "Rehabilitation" , "Revenue Cycle" , "Seniors" , "Social Services" , "Treatment" , "Utilization Management" , "Wound Care"], title -> Nursing Supervisor/Outreach Coordinator, title_normalized -> NURSING SUPERVISOR OUTREACH COORDINATOR, geopoint -> Map(lat -> 42.3584308, lon -> -71.0597732))] using writer [org.elasticsearch.spark.serialization.ScalaValueWriter@2c0dd2d4]
```

**Comment by costin** [comment] 2015-02-01 23:07
@jfelectron What version are you using? Just tried reproducing this with maps of maps and lists and works fine. Can you please create a small test case to reproduce the problem?

Thanks

**Comment by jfelectron** [comment] 2015-02-01 23:11
Recent snapshot.

I'm taking a BasicDBObject from Mongo/Casbah, transforming some of the fields and outputting an immutable Map.

This isn't really a test case, so much as a snippet of the code that leads to the exception. I can put together something better. 

  override def prep_for_indexing(doc: BasicDBObject) = {
    val date_fmt = DateTimeFormat.forPattern("yyyy-MM-dd")
    val trans_doc = transform_doc(doc, "uuid")
    val indexable = trans_doc.filter { case (k, v) => fields_to_index.contains(k)}
    // fix datestamps
    indexable.iterator.map { case (k, v) => {
      k match {
        case "start_date" => (k, DateTime.parse(v.toString, date_fmt))
        case "geopoint" => (k,geo_map(v.asInstanceOf[BasicDBObject]))
        case _ => (k,v)
      }
    }
    }.map{case(k,v)=>(k,v.asInstanceOf[AnyRef])}.toMap
  }

  def geo_map(geopoint: BasicDBObject): Map[String,AnyRef] = {

    geopoint.iterator.map { case (k, v) =>  (k,v) }.toMap
  }

**Comment by costin** [comment] 2015-02-02 11:07
// did some minor edits to your post to add formatting to make the posts readable.

I'm pretty sure the issue is with the `Map` content - in this case the `org.joda.time.DateTime` object that you create for `start_date`.
The exception is a bit misleading since:
- the `ValueWriter` returns the document/entry that could not be serialized even though it might be just an entry of it. This makes it easy to identify the _area_ where it occurs but not to pinpoint the issue. I'll see if I can do something about it
- in case of an exception, it calls `toString` on the target object. You can see the 'containing' class - the `Map` but not the classes it holds and that trigger the exception.

**Comment by jfelectron** [comment] 2015-02-02 16:53
@costin ahh Correct! Sorry for the noise here. I ended up just transforming to JSON myself and while that worked it led me to realize that I had forgot to transform the DateTime object :/.

**Comment by costin** [comment] 2015-02-02 18:24
@jfelectron Nevertheless, the error message was not clear enough, which is why I raised #370. It has been addressed in master and a new dev build pushed in Maven.
Can you please try it out?
Cheers,

**Comment by jfelectron** [comment] 2015-02-02 19:51
@costin Looks good. :+1:  I can check this, I"l have to roll back to the version that raised the exception.

**Comment by costin** [comment] 2015-02-13 21:10
@jfelectron any update? can I close this issue?

**Comment by costin** [comment] 2015-04-28 14:35
Closing the issue...

**Closed by costin** 2015-04-28 14:35 UTC
Labels: invalid, spark, v2.1.0.Beta4
