### ISSUE TITLE
Position for 'params.expo_cnt' not found in row; typically this is caused by a mapping inconsistency

### ISSUE THREAD

**Issue by pnuzyf** [elastic/elasticsearch-hadoop#1437] opened 2020-03-07 07:07 UTC
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description
org.elasticsearch.hadoop.rest.EsHadoopParsingException: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Position for 'params.expo_cnt' not found in row; typically this is caused by a mapping inconsistency
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:514)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:292)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:262)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:313)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:93)
Description
 when read data from es, I got the above error. mapping file:
```
"mappings": {
  "all": {
    "properties": {
      "ftime": {
        "type": "long"
      },
      "metadata": {
        "properties": {
          "fduration": {
            "type": "long"
          }
        }
      },
      "gvid": {
        "type": "text",
        "fields": {
          "keyword": {
            "ignore_above": 256,
            "type": "keyword"
          }
        }
      },
      "params": {
        "properties": {
          "share_cnt": {
            "type": "long"
          },
          "valid_play_cnt": {
            "type": "long"
          },
          "expo_cnt": {
            "type": "long"
          },
          "strict_full_play_cnt": {
            "type": "long"
          },
          "follow_cnt": {
            "type": "long"
          },
          "notlike_cnt": {
            "type": "long"
          },
          "full_play_cnt": {
            "type": "long"
          },
          "loose_full_play_cnt": {
            "type": "long"
          },
          "like_cnt": {
            "type": "long"
          },
          "play_cnt": {
            "type": "long"
          },
          "playtime_sum": {
            "type": "long"
          }
        }
      }
    }
  }
},
```
### Steps to reproduce

Code:
spark = SparkSession
      .builder()
        .config("es.nodes", Configuration.es_video_nodes)
            .config("es_port", Configuration.es_port)
      .enableHiveSupport()
      .getOrCreate()
val df = EsSparkSQL.esDF(spark, Configuration.index)
df.show(10)
```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  2.3.1
ES-Hadoop   :  7.0
ES          :  7.0

**Comment by jbaiera** [comment] 2020-03-09 16:50
Thanks for opening an issue. Can you provide some testing data here that reproduces your error?

**Comment by pnuzyf** [comment] 2020-03-12 12:39
"_source" : {
          "ftime" : 20200308161000,
          "params.expo_cnt" : 0,
          "params.strict_full_play_cnt" : 0,
          "params.valid_play_cnt" : 2,
          "params.share_cnt" : 0,
          "params.loose_full_play_cnt" : 2,
          "params.notlike_cnt" : 0,
          "params.playtime_sum" : 190,
          "params.like_cnt" : 0,
          "params.follow_cnt" : 0,
          "gvid" : "r01854c8m1n",
          "metadata.fduration" : 1000,
          "params.play_cnt" : 2,
          "params.full_play_cnt" : 0
        },
"_source" : {
          "ftime" : 20200308160500,
          "params.expo_cnt" : 0,
          "params.strict_full_play_cnt" : 0,
          "params.valid_play_cnt" : 1,
          "params.share_cnt" : 0,
          "params.loose_full_play_cnt" : 1,
          "params.notlike_cnt" : 0,
          "params.playtime_sum" : 88,
          "params.like_cnt" : 0,
          "params.follow_cnt" : 0,
          "gvid" : "r01854c8m1n",
          "metadata.fduration" : 1000,
          "params.play_cnt" : 1,
          "params.full_play_cnt" : 0
        }

**Comment by pnuzyf** [comment] 2020-03-24 11:03
is there any progress?

**Comment by blackvvine** [comment] 2020-05-07 19:15
I'm experiencing the same problem in loading an index of Zeek logs using ES Hadoop:

```python
reader = spark.read.format("org.elasticsearch.spark.sql").option("es.read.metadata", "true")
for k, v in es_read_conf.items(): reader = reader.option(k, v)

df = reader.load("foo")
df.count()
```

Gives:

```
Py4JJavaError: An error occurred while calling o634.count.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 513 in stage 33.0 failed 4 times, most recent failure: Lost task 513.3 in stage 33.0 (TID 11503, ontario.atlas.cs.uwaterloo.ca, executor 172): org.elasticsearch.hadoop.EsHadoopIllegalStateException: Position for 'enrichments:geo:ip_dst_addr:locID' not found in row; typically this is caused by a mapping inconsistency
	at org.elasticsearch.spark.sql.RowValueReader$class.addToBuffer(RowValueReader.scala:60)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToBuffer(ScalaEsRowValueReader.scala:32)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToMap(ScalaEsRowValueReader.scala:118)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:810)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:700)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:466)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:391)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:286)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:259)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:365)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:92)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:299)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2831)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2830)
	at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3365)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3364)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2830)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Position for 'enrichments:geo:ip_dst_addr:locID' not found in row; typically this is caused by a mapping inconsistency
	at org.elasticsearch.spark.sql.RowValueReader$class.addToBuffer(RowValueReader.scala:60)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToBuffer(ScalaEsRowValueReader.scala:32)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToMap(ScalaEsRowValueReader.scala:118)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:810)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:700)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:466)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:391)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:286)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:259)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:365)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:92)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

(<class 'py4j.protocol.Py4JJavaError'>, Py4JJavaError('An error occurred while calling o634.count.\n', JavaObject id=o635), <traceback object at 0x7f98c31c1b48>)

```

Needless to say, I can still work around it using `sc.newAPIHadoopRDD` to load the search results as an RDD and then converting to DF:

```python

from pyspark.sql import Row

es_rdd = sc.newAPIHadoopRDD(
    inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
    keyClass="org.apache.hadoop.io.NullWritable",
    valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", 
    conf=es_read_conf)

df = es_rdd.map(lambda x: Row(**x[1])).toDF()
```

But working out the schema manually is a huge pain and honestly, this way, ES Hadoop doesn't add a lot of value compared to just manually loading search results using [elasticsearch](https://elasticsearch-py.readthedocs.io/en/master/) in workers.

**Comment by jbaiera** [comment] 2023-06-29 18:55
Closing this as a duplicate of #853

**Closed by jbaiera** 2023-06-29 18:55 UTC
Labels: feedback-requested
