### ISSUE TITLE
failed in inserting into elasticsearch table on cdp

### ISSUE THREAD

**Issue by hfsugar** [elastic/elasticsearch-hadoop#2100] opened 2023-06-12 01:27 UTC
### What kind an issue is this?
ClassNotFoundException bug when inserting into es table on cdp.

### Issue description

Sqls below are executed on cdp by engine tez. Created table succeed, but failed when inserting into es table.

### Steps to reproduce

Code:
```
add jar elasticsearch-hadoop-hive-7.1.1.jar;
CREATE TABLE IF NOT EXISTS test.history_deliver_es( fund_account string,
                              rowkey string )
                              STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
                              TBLPROPERTIES('es.resource' = 'test/history_deliver_es',
'es.index.auto.create' = 'true',
"es.mapping.id" = "fund_account",
'es.mapping.names' = 'fund_account:fund_account, rowkey:rowkey',
'es.nodes.wan.only'='true',
'es.batch.write.retry.count'='10',
'es.batch.write.refresh'='true',
'es.batch.write.retry.wait'='60s',
'es.http.timeout'='100m',
'es.batch.size.entries'='100',
'es.nodes' = '192.25.109.213:9200,192.25.109.214:9200,192.25.109.215:9200,192.25.109.216:9200,192.25.109.217:9200');

insert into table test.history_deliver_esvalues('test','test');
```
```
Strack trace:
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpConnectionManager
at [java.net](http://java.net/).URLClassLoader.findClass([URLClassLoader.java:381](http://urlclassloader.java:381/)) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass([ClassLoader.java:424](http://classloader.java:424/)) ~[?:1.8.0_181]
at sun.misc.Launcher$AppClassLoader.loadClass([Launcher.java:349](http://launcher.java:349/)) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass([ClassLoader.java:357](http://classloader.java:357/)) ~[?:1.8.0_181]
at [org.elasticsearch.hadoop.rest](http://org.elasticsearch.hadoop.rest/).commonshttp.CommonsHttpTransportFactory.create([CommonsHttpTransportFactory.java:40](http://commonshttptransportfactory.java:40/)) ~[elasticsearch-hadoop-hive-7.1.1.jar:7.1.1]
at [org.elasticsearch.hadoop.rest](http://org.elasticsearch.hadoop.rest/).NetworkClient.selectNextNode([NetworkClient.java:102](http://networkclient.java:102/)) ~[elasticsearch-hadoop-hive-7.1.1.jar:7.1.1]
at [org.elasticsearch.hadoop.rest](http://org.elasticsearch.hadoop.rest/).NetworkClient.<init>([NetworkClient.java:85](http://networkclient.java:85/)) ~[elasticsearch-hadoop-hive-7.1.1.jar:7.1.1]
at [org.elasticsearch.hadoop.rest](http://org.elasticsearch.hadoop.rest/).NetworkClient.<init>([NetworkClient.java:61](http://networkclient.java:61/)) ~[elasticsearch-hadoop-hive-7.1.1.jar:7.1.1]
``` 

### Version Info

OS:         :  
JVM         :  1.8
Hadoop/Spark:  cdp 7.4.4 
ES-Hadoop   :  elasticsearch-hadoop-hive-7.1.1
ES          :  7.1.1

**Comment by jbaiera** [comment] 2023-06-12 03:52
Please make sure that you have all dependencies that ES-Hadoop expects available on the Hive classpath. You likely are missing a dependency on https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient/3.1.

Given that this is likely a configuration problem and not a bug I'm closing this issue out.

**Closed by jbaiera** 2023-06-12 03:52 UTC
