### ISSUE TITLE
Adding  specific Spark partitioner  implematation to speed Bulk  

### ISSUE THREAD

**Issue by allwefantasy** [elastic/elasticsearch-hadoop#745] opened 2016-04-14 02:55 UTC
It seens if we can partitions data by sharding algrithom from ES in spark, 
es-hadoop bulk QPS will be double.

This kind of preprocessing have benefit like these:
- avoid N*N times communication between ES Nodes
- avoid consuming to much bulk thread in ES

However, this means parition num in spark is equal to shard num in ES. So we also can map multi paritions to one shard ,like this:

```
//variable shardToPartitions means how many paritions are mapped to one shard
class ESShardPartitioner(settings:String) extends Partitioner {
      protected val log = LogFactory.getLog(this.getClass())

      protected var _numPartitions = -1 
      protected var shardToPartitions = 1

      override def numPartitions: Int = {   
        val newSettings = new PropertiesSettings().load(settings)
        val repository = new RestRepository(newSettings)
        val targetShards = repository.getWriteTargetPrimaryShards(newSettings.getNodesClientOnly())
        repository.close()
        if(newSettings.getProperty("es.bulk.shard.partitions") !=null ){
          shardToPartitions = newSettings.getProperty("es.bulk.shard.partitions").toInt          
        }
        _numPartitions = targetShards.size()                        
        _numPartitions * shardToPartitions
      }

      override def getPartition(key: Any): Int = {
        val shardId = ShardAlg.shard(key.toString(), _numPartitions)        
        val paritions = ((shardId * shardToPartitions) until (shardId * shardToPartitions + shardToPartitions)).toList
        val targetPartitionId = Random.shuffle(paritions).head        
        targetPartitionId
      }
}

object ESShardPartitioner {

def shardIdFromPartitionId(partitionId:Int,shardToPartitions:Int):Int={
     if (partitionId < shardToPartitions) return 0 
      partitionId / shardToPartitions   
   } 
   .....
   }     
```

In order to  support this, we add a new property:

```
String  ES_BULK_SHARDID = "es.bulk.shardid";
```

And make some changes in RestService.initSingleIndex 

```
if(settings.getProperty(ConfigurationOptions.ES_BULK_SHARDID) != null){       
            targetNode = targetShards.get(orderedShards.get(Integer.parseInt(settings.getProperty(ConfigurationOptions.ES_BULK_SHARDID))));
        }
```

Now we can use like this:

```
.partitionBy(new ESShardPartitioner(settings)).mapPartitionsWithIndex { (partionId, iter) =>
    val shardId = ESShardPartitioner.shardIdFromPartitionId(partionId, shardToPartitions)
    settings.setProperty("es.bulk.shardid",targetShardId.toString())
    val writer = EsSpark.createEsRDDWriter[Map[String,String]](settings)   
    writer.write(TaskContext.get(), shardId, iter.map(f => f._2))


.....
}
```

**Comment by costin** [comment] 2016-04-14 17:05
Thanks for raising this (and providing the code).

Just trying to understand better the problem and the proposed solution.
1. When do you want to repartition, when there are more ES shards than Spark paritions, or vice versa? Or do you want to partition all the time?
Because I'm trying to understand what are the improvements and whether you have some numbers that show the increase QPS.

> avoid N*N times communication between ES Nodes

Where does this come from? The bulk write talks to primaries which in turn talk to the other nodes; the communication between the nodes is likely to exist anyway. Further more, for all docs to sit on one shard and not be redirected, one would have to replicate the hashing function in ES and apply it on 
_each_ doc. 
This has several downsides such as:
 ~ _each_ client task would communicate with all nodes in ES. So you would have C * N communications where C is client tasks and N ES nodes.
~ _each_ client would need to have separate bulk queues for _each_ target node.
~ the semantics will change since the docs would be added differently (once each N queue fills up).

This work is currently done much more reliably and faster in ES - moving this to the client has no real benefits.

> avoid consuming to much bulk thread in ES
Again, where does this come from? Do you have some numbers on this happening?

Maybe I'm missing something obvious.

Cheers,

**Comment by allwefantasy** [comment] 2016-04-15 01:54
Once we have done the transformation ,we can repartion by ESShardPartitioner,then we 
use `mapPartitionsWithIndex` to do real save action.

After repartion, the number of  Spark partitions is always >= ES shards,however maybe some partitions in spark are empty.

Suppose we have one partion called A. All data in A will belongs to one Shard,and we know where is the targetShard. So Es node who receive data will have no need to commute with other ES node in order to bulk data belongs to others. Here is why the QPS will increate.

```
.partitionBy(new ESShardPartitioner(settings)).mapPartitionsWithIndex { (partionId, iter) =>
```

> 1. When do you want to repartition, when there are more ES shards than Spark paritions, or vice versa? Or do you want to partition all the time?
Because I'm trying to understand what are the improvements and whether you have some numbers that show the increase QPS.



Since ES node recives data from client,it will send data to other nodes. If we make sure all data from client belongs to this ES node,then we can reduce commucations between nodes. 

> Where does this come from? The bulk write talks to primaries which in turn talk to the other nodes; the communication between the nodes is likely to exist anyway. 

Yes ,now we only resolve primary shard. 

> Further more, for all docs to sit on one shard and not be redirected, one would have to replicate the hashing function in ES and apply it on 
each doc. 


Every partition in spark only have one client who commucate with one ES Node.
So the total connection is  C where C is client paritions（not tasks）

> ~ each client task would communicate with all nodes in ES. So you would have C * N communications where C is client tasks and N ES nodes.

Since we have repartition the docs which means very partition only have one bulk action

> ~ each client would need to have separate bulk queues for each target node.

> ~ the semantics will change since the docs would be added differently (once each N queue fills up).

we try to reduce the presure of ES Node and reduce network commucation(no need to use ES client Node).And spark repartion is very quick.
> This work is currently done much more reliably and faster in ES - moving this to the client has no real benefits.

here is the ShardAvg:

```
public class ShardAlg {
    public static int shard(String id, int shardNum) {
        int hash = Murmur3HashFunction.hash(id);
        return mod(hash, shardNum);
    }

    public static int mod(int v, int m) {
        int r = v % m;
        if (r < 0) {
            r += m;
        }
        return r;
    }
}

```
```

**Comment by allwefantasy** [comment] 2016-04-15 02:01
I have already provided the  completely ESShardPartitioner in the first comment.

**Comment by costin** [comment] 2016-04-15 15:42
I see. The culprit is here:

```
    public static int shard(String id, int shardNum) {
        int hash = Murmur3HashFunction.hash(id);
        return mod(hash, shardNum);
    }
```

What is `id`? When ES decides where a document should be it performs hashing and yes, depending on the ES version used, Murmur3 is used. The issue however is that the hashing is applied on the ID which, in most cases, is autogenerated by ES.
That is, the id in Spark or your app, is not the same as the actual ID of the doc in ES (and in most cases you don't want it to be); one can set the id manually but ES internally is moving away from that as its own IDs can and do have stronger guarantees.
So while a custom `Partitioner` does sort data, the problem is it has no impact on ES itself since there is no way a client can autogenerate the same ID (in ES the generation is done on the coordinating node and implies some randomness to it, specific to that node).

So in the end, as a client, unless the ID is known (which is not always the case) and the client knows the exact ES version (the hashing has changed between major versions), realistically the extra partitioning is just extra work without any effect.
That's why I asked about your numbers because I'd like to replicate them especially since:
> es-hadoop bulk QPS will be double.

Cheers,

**Comment by allwefantasy** [comment] 2016-04-16 14:30
Exactly,for now it  only works when the ID is known and  the client should know exact ES version. 
We can check some requirements when user using this feature.
> So in the end, as a client, unless the ID is known (which is not always the case) and the client knows the exact ES version (the hashing has changed between major versions), realistically the extra partitioning is just extra work without any effect.

**Comment by garyelephant** [comment] 2016-04-18 01:50
+1

**Comment by allwefantasy** [comment] 2016-04-19 03:28
The key concept is to migrate some features from ES to es-hadoop project,so we can make full use of computing power in spark . To resolve the issue you mentioned which has no any effect when the ID is auto generated by ES ,we can have a proposal for es team to support externalAutoGeneratedId. With this feature we can also leverage the performance with no lock create in ES.

codes like follow:
```
if (engineConfig.isOptimizeAutoGenerateId() &&( create.autoGeneratedId() || create.externalAutoGeneratedId) && !create.canHaveDuplicates()  ) {
            // We don't need to lock because this ID cannot be concurrently updated:
            innerCreateNoLock(create, Versions.NOT_FOUND, null);
        }
```

**Comment by jbaiera** [comment] 2018-03-29 17:29
I'm moving discussion here to #1130

**Closed by jbaiera** 2018-03-29 17:29 UTC
Labels: :Spark, enhancement
