### ISSUE TITLE
Spark throwing an exception as "org.elasticsearch.hadoop.rest.EsHadoopTransportException: java.net.BindException"

### ISSUE THREAD

**Issue by Prashant-Pal** [elastic/elasticsearch-hadoop#570] opened 2015-10-12 07:04 UTC
Hi Team,

I am using elasticsearch-hadoop with the spark for events processing.

So when we are processing the events with 3 evt per second I am able to do the same successfully but when bandwidth is increased to 5 times that is 15 events per second then i am getting the below exception. 

15/10/12 10:42:15 ERROR JobScheduler: Error running job streaming job 1444626720000 ms.1
org.elasticsearch.hadoop.rest.EsHadoopTransportException: java.net.BindException: Address already in use
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:121)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:317)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:313)
        at org.elasticsearch.hadoop.rest.RestClient.count(RestClient.java:392)
        at org.elasticsearch.hadoop.rest.RestRepository.count(RestRepository.java:456)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.count(AbstractEsRDD.scala:49)

This seems the issue like sockets are not getting closed after the operation so what is the param or how we can close the sockets.
 Below is the API I am using for search : 
JavaEsSpark.esRDD(sc, "json_events/events").count();

Let me know if anyone has any info for the same.

**Comment by costin** [comment] 2015-10-12 08:42
Looks like a connection leak. What version of es-hadoop are you using? Anything appearing in the logs before the operation?
How many times are you calling the count method? The RDD doesn't keep a persistent connection - it only opens one up when having to iterate; the connection is closed once the iterator is consumed or the job finished.

In 2.1.1, the `count` method has also been optimized so rather then pulling in all the data, it returns the result on the spot.
Outside a connection leak (which might be a bug), the only other reason I can think of is that for each even a processing is started which creates a connection to ES. Under load, there are simply too many connections at once causing the exception to occur.

Really the workaround in that case is to limit the number of connections - that is call it every X events not for each one simply it's simply too expensive.

**Comment by Prashant-Pal** [comment] 2015-10-12 08:51
Hi Costin,

I am using version 2.1.1. Before the operation the logs are as below : 
15/10/12 13:29:53 INFO BlockManagerInfo: Added input-0-1444636792800 in memory on localhost:47598 (size: 1117.0 B, free: 265.0 MB)
15/10/12 13:29:53 INFO BlockManagerMaster: Updated info of block input-0-1444636792800
15/10/12 13:29:53 WARN BlockManager: Block input-0-1444636792800 replicated to only 0 peer(s) instead of 1 peers
15/10/12 13:29:53 INFO BlockGenerator: Pushed block input-0-1444636792800
15/10/12 13:29:54 INFO MemoryStore: ensureFreeSpace(2193) called with curMem=177221, maxMem=278019440
15/10/12 13:29:54 INFO MemoryStore: Block input-0-1444636793800 stored as bytes in memory (estimated size 2.1 KB, free 265.0 M


Count method is being called about 600 times a second. But as this will be calling elastic-hadoop function to create the socket and send to Elasticsearch, so there might be the case like connection is not getting closed once the request is being fulfilled or the iterator is consumed or the job finished.


Yes , while i am checking the same netstat -anl | grep 9200 , I can see lot of connections in TIME_WAIT means the previous connections are not closed even though job is finished and now system is not having any port to send new connection request (Also we are performing all operations sequentially so connection should also get closed after request is being completed)?

So what do you think could be the solution to this ?

**Comment by costin** [comment] 2015-10-12 11:26
I've discovered an issue with the way the connection is closed and pushed a fix for it - can you please try the latest [dev build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev)?
Note that in my tests, closing the connection seems to be just postpone the exception - the OS still runs out of connections (it depends how fast the OS is configured to release the socket after the TCP connection has been closed).

Thanks,

**Comment by Prashant-Pal** [comment] 2015-10-12 11:40
Hi Costin,

The build which you have provided at above link is still failing with below error logs.

15/10/12 17:07:03 INFO SparkContext: Starting job: foreach at Spark_ES_V4.java:47
Error: application failed with exception
org.elasticsearch.hadoop.rest.EsHadoopTransportException: java.net.BindException: Address already in use
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:121)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:333)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:325)
        at org.elasticsearch.hadoop.rest.RestClient.count(RestClient.java:412)
        at org.elasticsearch.hadoop.rest.RestRepository.count(RestRepository.java:503)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.count(AbstractEsRDD.scala:49)
        at org.apache.spark.api.java.JavaRDDLike$class.count(JavaRDDLike.scala:420)
        at org.apache.spark.api.java.AbstractJavaRDDLike.count(JavaRDDLike.scala:46)
        at org.paladion.atm.Spark_ES_V4$2.call(Spark_ES_V4.java:204)
        at org.paladion.atm.Spark_ES_V4$2.call(Spark_ES_V4.java:81)
        at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:311)
        at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:311)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1.apply(DStream.scala:534)
        at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1.apply(DStream.scala:534)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:42)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
        at scala.util.Try$.apply(Try.scala:161)
        at org.apache.spark.streaming.scheduler.Job.run(Job.scala:32)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:176)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:176)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:176)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.BindException: Address already in use
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
        at java.net.Socket.bind(Socket.java:644)
        at java.net.Socket.<init>(Socket.java:433)
        at java.net.Socket.<init>(Socket.java:286)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:417)
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:104)
        ... 26 more

Let me know if you require any other info to analyze the same.

Thanks,

**Comment by costin** [comment] 2015-10-12 12:29
You can turn on logging on `org.apache.commons.httpclient` package (all the way to `TRACE`) to see that the connection is indeed closed. If that is indeed in the case, there's not much else that can be done at least in the official distro.
Basically you are opening way too many connections per second - either you stop doing that or reuse the connection between calls. If the count is all that you need, you can do the REST call yourself to get the number and reuse the connection within your code.

The RDD usage becomes too expensive in your case since really you aren't using any of its feature and further more, due to its lifecycle, the underlying connection cannot be shared across calls.

**Comment by Prashant-Pal** [comment] 2015-10-12 12:45
Actually we need to call count function for about 600 times per second, so how I can avoid opening too many connections per second or reuse the connection between calls.

As I just need the count so i am using long abc = JavaEsSpark.esRDD(sc, "json_events/events").count();.... Is there any alternative to do same without opening too many connection?

And to the REST call i need to send POST request and that will return the JSON response which again need to be parsed, So do you have any info which REST call can return only count with no other things as output?

Also which functions to be invoked from the package org.apache.commons.httpclient to trace the logs

**Comment by costin** [comment] 2015-10-12 13:02
Calling count 600/s is just  a complete waste of resources. I assume you are trying to double check whether the data went in but you already know this if POST request has succeeded.
Stepping aside for a bit, calling a service (whether it's Elastic or something else) 600 per second for a counter is simply way too ... unoptimal. 
Use your own counter instead and use that instead - that is instead of calling count 600/s, call it every 2s or 5s and expect it to be 1200 or 3000 items more.
Batches are your friend.

The documentation on REST and the API in Elasticsearch can be easily found in the docs - no need to reproduce them here. And yes, you do have to do parsing of the data. 
However the [cat api](https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-count.html) might be useful as it is meant for the command-line.

Last but not least, turning on logging implies configuring log4j which means specifying a parameter within its configuration file. Again, there's plenty of documentation out there including in Spark itself.

I'm going to close the issue as the underlying bug (discovered through this issue) was fixed and your request can't be addressed by the project. For further discussions, please see the [forum](discuss.elastic.co).
I maintain my recommendation to rethink a bit your block of code since a write is acknowledged once it is being performed, there's no need to verify it again. And writing multiple events/data at once is better for all parties then writing it one by one. The bigger the batch, the better the performance.

**Closed by costin** 2015-10-12 13:02 UTC
Labels: question, spark, v2.1.2, v2.2.0-m2

**Comment by Prashant-Pal** [comment] 2015-10-12 13:29
Hi ,

Here i am not performing the count for same query, as I am using the count as long cnt = JavaEsSpark.esRDD(sc, "json_events/events",strQuery).count(); as well.

So here in a second 600 different search queries are being fired to ES using param "strQuery". So all 600 queries perform search on various combination and give the output.

Yes, we have gone through with the _cat, and that will not be suffice as that gives the count and all wrt complete cluster not to particular query. And here count we are fetching with search query output as well because fetching the .value() instead of .count() will be too costly.

Do you think if any better way is there to perform search query and get output without using the above mentioned count method.

~Prashant
