### ISSUE TITLE
Nested field with camel case in elasticsearch were not supported. 

### ISSUE THREAD

**Issue by AmirSabjan** [elastic/elasticsearch-hadoop#1341] opened 2019-08-30 03:16 UTC
https://github.com/elastic/elasticsearch-hadoop/blob/2acafc08c61ddacfbd14aaac4ab52aca670c9103/hive/src/main/java/org/elasticsearch/hadoop/hive/HiveUtils.java#L110

Need support to get the caseInsensitive settings passed from hive, as hive supports only lowercase column names for complex objects fields and this restricts to have the lower case in the Elasticsearch nested fields also.

**Comment by jbaiera** [comment] 2019-09-04 18:19
@AmirSabjan Thanks for opening an issue here. Could you reformat it with the provided template and some reproduction details? Issues with short descriptions like this one are hard for developers to fully understand what the problem is.

**Comment by jbaiera** [comment] 2019-09-23 16:34
Closing this out since there hasn't been any further feedback. If you feel like this is still an issue, we can re-open it and investigate it further, but it sounds like the limitation here is with Hive more than ES-Hadoop.

**Closed by jbaiera** 2019-09-23 16:34 UTC
Labels: feedback-requested
