### ISSUE TITLE
Document Count in ES Different from Number of Entries Pushed

### ISSUE THREAD

**Issue by mparker4** [elastic/elasticsearch-hadoop#283] opened 2014-09-26 17:58 UTC
We are seeing an issue where the number of documents successfully created/indexed in ES is different  (more--very odd, or less) from the number of documents which we are giving ES to index. 

Specifically, we are using spark to grab specific correctly formatted json from a repository and simply write it to ES into a new index. The difference in documents only seems to occur if there is a large number of documents being inserted (specifically we tested with 929,660) and too few shards (specifically 1). We also did a test at a larger scale (roughly 9 million documents and over 100 shards) which also gave incorrect document counts. We have ruled out this being a spark issue, but  there are no apparent issues or exceptions in the logs (ES or Spark/ES-Hadoop), including when they are upped to debug. We do notice that ES does throttle the input. The fact that this only happens when large numbers of documents are created/indexed and that it seems to alleviate when more shards are added to balance the load points it to a load issue. I believe this to be an issue with ES core, but I was interested in seeing if anyone else here had seen this due to ES-hadoop being able to create a load issue more easily than the normal api. We have tried ES-hadoop 2.1.0-beta and 2.0.1 release with the same results.

I can provide more details as needed, but as there is nothing in the logs, there are not many other observables that I can detail. It is very similar to: http://elasticsearch-users.115913.n3.nabble.com/missing-documents-after-bulk-indexing-td4056100.html, however I  am not seeing any exceptions. Please let me know if anyone has seen this issue or has any resolution.

**Comment by costin** [comment] 2015-01-07 20:06
@b0c1 Thanks for the sample dataset - I've managed to reproduce the bug and fix it. I've pushed out the new binaries - can you please try them out and report back?

@bzz Can you please try the latest binaries as well and see whether it fixes your problem? Can please try several scenarios: removing the patterns from the index name and indexing everything under the same index and see whether that makes any difference. Adding a path id (as suggested by @mparker4). Also between your runs, can you spot what documents are missing - are there any shards that stand out (whether some have the same number of documents or not).
Do you have any sample of documents that I could try? Maybe reduce the number of documents to 10K or less and see whether it's reproducible.
Anything special about your cluster - number of nodes vs machines etc?

P.S. The exact number of 5 makes me think about the default sharding in elasticsearch. How many Spark tasks do you have by the way? If it helps, give me a ping on IRC maybe it helps getting down to the root of the problem.

@mparker4 Hopefully you're still around - can you please try out the latest 2.1 build and report back; it looks like you were using the id mapping and the latest build fixes that (so you can use it as an alternative to path ids in Elasticsearch).
As for the internal stats to be exposed in Spark, it looks like the library provides a metrics package but I haven't seen much use of it. If there is any, we could easily provide the internal es-hadoop stats there, just as we do with Map/Reduce in Hadoop.

**Comment by costin** [comment] 2015-01-07 20:17
@mparker4 By the way, there is a chance that under load you _might_ have hit these Elasticsearch bugs, namely elasticsearch/elasticsearch#9125 and elasticsearch/elasticsearch#7729. These are fixed in ES master.

**Comment by bzz** [comment] 2015-01-12 08:38
@costin thanks for taking care, I'm working on providing an reproducible environment for you.

Latest code gives the same x5 number of documents written. BUT this happens _only_ when custom mapping is provided (and applied well, by the template). 

Funny enough, exactly same happens if I switch to ```TransportClient``` with BULK API, indexing same RDD from the SparkDriver after ```.collect()```
Even more funny is that this x5 effect persists in case I do NOT bulk but index every document.

Without the template (so no mapping set) it works well - the number of documents is same as number of RDD elements.

**Comment by costin** [comment] 2015-01-12 09:41
@bzz so it looks like you are using spark and elastic without es-hadoop, correct (since you mention the `TransportClient`). Do you use es-hadoop for anything (like reading the data once it is indexed) or not really?
I'm just trying to understand your environment.

The consistent x5 might indicate an over indexing - that is the data is indexed multiple times (potentially by each Spark task). The custom mapping might trigger that if it contains a different id strategy causing documents that otherwise would be merged to be added. Just a guess...
You might be also hitting the two ES bugs mentioned above.

**Comment by costin** [comment] 2015-01-12 14:06
@b0c1 @mparker4 hey guys - can you please check out the latest changes?

**Comment by bzz** [comment] 2015-01-13 06:20
@costin thanks for helping
> Do you use es-hadoop for anything (like reading the data once it is indexed) or not really?

I use es-hadoop with Scala native api since it became available to write to single-node ES 1.4.2 cluster, but as result got x5 documents written
  - so I switched to using ```TranspportClient``` + batch api instead of es-hadoop to check if that's an es-hadoop issue, but still had x5 docs. After you'v mention known ES bugs of the bulk api I was not aware of
  - so I switched to ```TranspportClient``` +  indexing each document separately to check if I hit any of those bugs and still had x5 documents

Only then I got rid of template with custom mappings and start getting correct number of documents written (any technique from above works now)

I guess there are strong evidence now that my case is not issue of es-hadoop so I'll be moving this to elasticseach mailing list.

**Comment by costin** [comment] 2015-01-26 11:23
@bzz Any update on this front? do you use aliases by any chance?

**Comment by bzz** [comment] 2015-02-02 01:14
No aliases and I still see the number of documents reported by ES x5 from the ```rdd.count```.
At the same time, on reading from those indexes using es-hadoop, on the spark side ```esEsRdd.count``` will show the original number..

**Comment by costin** [comment] 2015-02-02 11:00
The x5 makes me think that this has something to do with the number of shards for the target index. es-hadoop does the count per shard while in your case, you might be indexing _all_ the documents in _each_ task and thus you end up doing 5 times the work hence the multiplier.

**Comment by mparker4** [comment] 2015-03-20 17:15
@costin Sorry I haven't been paying attention here. We had to go an entirely different route in our architecture based on this and some other requirements so we're not using es-hadoop at the moment but will probably look into it again in the future (when other priorities settle down). Unfortunately it is difficult for me to test the issue now this seeing our architecture has changed so much, but I will put it on the back burner to try. If problems are fixed for bzz and others, feel free to close this if you would like. I can reopen at a later date if anything arises. Thanks for all the help.

**Comment by costin** [comment] 2015-04-28 14:44
@bzz @b0c1 @mparker4  Thanks for the updates, I'll close the issue for now. If the issue occurs in the future, please open up a new one while potentially linking to this one.

Cheers,

**Closed by costin** 2015-04-28 14:44 UTC
Labels: bug, rest, v2.0.3, v2.1.0.Beta4

**Comment by swatisaini** [comment] 2017-12-20 07:03
Hi @costin  ,

I'm getting the similar issue. There is mismatch found in document count while reading data from elasticsearch index using  pyspark code. 
Actual document count in elasticsearch is 991121(1.08 GB)  but when we read data into spark, at every attempt it keep changing. 
Number of shards - 5
replica - 0
following is the observations 
1 st try 991121
2nd try 991147
 3rd try 991095
Architecture version info 
spark version is 2.0.2
scala - 2.11
python 2.7 
elasticsearch 5.1.1
elasticsearch-spark connector-  20_2.11-5.1.1
