### ISSUE TITLE
Nested fields upsert with Spark not working

### ISSUE THREAD

**Issue by cristinaluengoagullo** [elastic/elasticsearch-hadoop#1190] opened 2018-08-30 12:11 UTC
Hi,

I already asked this a few months ago, but since the answer was that it would be fixed in a following release, I wanted to know whether I'm doing something wrong, or if it's still not fixed.

I'm trying to update a nested field using Spark and a scripted update. The code I'm using is:

update_params = "new_samples: samples"
update_script = "ctx._source.samples += new_samples"

es_conf = {
"es.mapping.id": "id",
"es.mapping.exclude": "id",
"es.write.operation": "upsert",
"es.update.script.params": update_params,
"es.update.script.inline": update_script
}

result.write.format("org.elasticsearch.spark.sql").options(**es_conf).option("es.nodes",configuration["elasticsearch"]["host"]).option("es.port",configuration["elasticsearch"]["port"] ).save(configuration["elasticsearch"]["index_name"]+"/"+configuration["version"],mode='append')

And the schema of the field is:

|-- samples: array (nullable = true)
| |-- element: struct (containsNull = true)
| | |-- gq: integer (nullable = true)
| | |-- dp: integer (nullable = true)
| | |-- gt: string (nullable = true)
| | |-- adBug: array (nullable = true)
| | | |-- element: integer (containsNull = true)
| | |-- ad: double (nullable = true)
| | |-- sample: string (nullable = true)

And I get the following error:

py4j.protocol.Py4JJavaError: An error occurred while calling o83.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.Tuple2

The full stack trace is:

Traceback (most recent call last):
  File "/home/cluengo/Documents/Projects/vcfLoader/python/rdconnect/main.py", line 151, in <module>
    main(hc,sqlContext)
  File "/home/cluengo/Documents/Projects/vcfLoader/python/rdconnect/main.py", line 141, in main
    variantsRN.write.format("org.elasticsearch.spark.sql").options(**es_conf).option("es.nodes",configuration["elasticsearch"]["host"]).option("es.port",configuration["elasticsearch"]["port"] ).save(configuration["elasticsearch"]["index_name"]+"/"+configuration["version"],mode='append')
  File "/home/cluengo/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 595, in save
  File "/home/cluengo/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in _call_
  File "/home/cluengo/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
   
  File "/home/cluengo/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o181.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 41.0 failed 1 times, most recent failure: Lost task 0.0 in stage 41.0 (TID 200, localhost, executor driver): java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.Tuple2
    at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
    at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.doWrite(AbstractBulkFactory.java:152)
    at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:118)
    at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)
    at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)
    at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:168)
    at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
    at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
    at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
 
Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
    at scala.Option.foreach(Option.scala:257)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:2075)
    at org.elasticsearch.spark.sql.EsSparkSQL$.saveToEs(EsSparkSQL.scala:101)
    at org.elasticsearch.spark.sql.ElasticsearchRelation.insert(DefaultSource.scala:610)
    at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:103)
    at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
    at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
    at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
    at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
    at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
    at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:280)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.Tuple2
    at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
    at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.doWrite(AbstractBulkFactory.java:152)
    at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:118)
    at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)
    at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)
    at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:168)
    at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
    at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
    at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:108)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    ... 1 more

Thanks so much!

**Comment by ebuildy** [comment] 2018-09-04 09:47
Hello, maybe you should post this on the forum or SO before here. I think this is an issue with your mapping and what you want to insert:

    java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.Tuple2

Can you add the mapping in the issue? Also, a useful way to debug Spark + ES is to use a HTTP Proxy (like Charles proxy), so you see exactly what the plugin does under the hood.

**Comment by jbaiera** [comment] 2018-09-04 18:07
This is indeed still an issue with the connector. The problem here is that we use our serialization code to write documents for bulk requests, but also to try and convert fields into values for use with scripting parameters. This leads to unique issues in Spark SQL, where we expect every object passed in to the serialization code to be a Tuple2 containing the object to be serialized (usually a row) and the schema for the row.

This isn't a problem for basic data types like strings or numbers since there is a check for that earlier in parameter generation code that handles those cases outside of the Spark-specific serialization code. Since you are trying to reference a complex datatype (an array in this case) the code tries to serialize the object according to how it would normally be done with SparkSQL, but it doesn't have the schema to give alongside the list, nor should it have to worry about it.

Ultimately, this is a bug that results from jamming a square peg in an almost-square hole. I'll try and prioritize a fix for this soon since I've seen the occurrences of this bug increase lately.

**Comment by cristinaluengoagullo** [comment] 2018-09-05 08:09
Ok, no problem! Thanks so much for the fast reply and the extensive answer :)

**Comment by satya-coup** [comment] 2018-09-21 05:01
I have a similar issue. Is there any work around for this issue.

**Comment by kyprifog** [comment] 2018-10-12 14:30
I am also hitting a situation where this being fixed would be really convenient.

**Comment by cristinaluengoagullo** [comment] 2019-02-15 11:59
Hi,
Just checking in to know whether there's any planning on when this bug would be solved. I'm hitting a point where it would be really convenient if this was fixed, but I understand there are many other issues that might have more priority.
Thanks!

**Comment by ggyyggyyggyy** [comment] 2019-04-03 12:40
Same issue. Hope it will be solved.

**Comment by erpic** [comment] 2019-06-07 13:39
Also stuck on this problem. I was hoping to encode non-trivial business logic for merging documents in a painless script. 

Initially hoping to work around by manually serializing my non-basic script parameters alas I cannot find any way to de-serialize inside the painless script.

Any visibility on allowing the passing of "other-than-basic-types" parameters? Many thanks!

**Comment by abdolence** [comment] 2019-06-13 20:52
bump into this too.
Is there any other way to upsert excluding/including some fields for update and using all of them for insert? Any workarounds?

**Comment by developedsoftware** [comment] 2019-10-14 15:44
Also just bumped into this issue. Any news on a fix?

**Comment by ankurmech** [comment] 2019-12-29 05:51
@jbaiera 

Is there fix yet as i am hold up with similar issue

Is there any workaround for this.?

**Comment by gsindholt** [comment] 2020-06-17 12:17
This issue appears to have been forgotten? Any chance that is will be fixed? Kind of a deal breaker in many circumstances...

**Comment by SivaSamrajS** [comment] 2020-10-06 09:59
Any update on this issue? Not able upsert the nested object into ES via Spark

**Comment by atomobianco** [comment] 2020-11-13 10:34
Hi,
having here the same/similar problem.
Updating with a `es.mapping.include` for a nested field writes empty objects.
Using Spark 2.4.4 and elasticsearch-spark-20 7.7.0

**Comment by sanjaysaini-msn** [comment] 2021-07-23 10:46
Please try to use

update_params = "new_samples:<samples>"

**Comment by masseyke** [comment] 2021-12-20 21:25
I'm able to reproduce this using the following snippet in spark shell:
```
import org.apache.spark.rdd._
import org.apache.spark.sql.types._
import org.apache.spark.sql._
val update_params = "new_samples: samples"
val update_script = "ctx._source.samples += new_samples"
val es_conf = Map("es.mapping.id" -> "id", "es.mapping.exclude" -> "id", "es.write.operation" -> "upsert", "es.update.script.params" -> update_params, "es.update.script.inline" -> update_script)
val sqlContext = new SQLContext(sc)
val data = Seq(Row("1", List(Row("hello"), Row("world"))))
val rdd: RDD[Row] = sc.parallelize(data)
val schema = new StructType().add("id", StringType, nullable = false).add("samples", new ArrayType(new StructType().add("text", StringType), true))
val df = sqlContext.createDataFrame(rdd, schema)
df.write.format("org.elasticsearch.spark.sql").options(es_conf).mode(SaveMode.Append).save("test")
```
I'll see if I can find a fix.

**Comment by masseyke** [comment] 2021-12-21 17:19
I've created a draft PR. I am not incredibly familiar with Elasticsearch's upsert functionality, so it fixes the specific problem in the description of this issue. I'd love feedback about whether people are running into cases that this doesn't fix.

**Closed** 2022-01-20 14:46 UTC
Labels: bug, :Spark, :Serialization
