### ISSUE TITLE
Pyspark  - scala.MatchError: null - ElasticSearch Nested mapping - Migrate from ES 5.6.3 to 6.8.3

### ISSUE THREAD

**Issue by visu0307** [elastic/elasticsearch-hadoop#1403] opened 2019-12-11 06:23 UTC
What kind an issue is this?

- [ x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

**Description**
I am using PySpark and  trying to migrate from Elasticsearch 5.6.3 to 6.8.3.
Please follow structure of one of the attribute in my nested mapping:
"availability": {
  "properties": {
       "current": {
         "properties": {
           "lastUpdateTm": { "type": "long" },
           "size": { "type": "keyword", "fields": { "keyword": { "type": "keyword", "ignore_above": 256 } } },
           "value": { "type": "long" }
         }
      },
      "previous": {
        "properties": {
          "lastUpdateTm": { "type": "long" },
          "size": { "type": "keyword", "fields": { "keyword": { "type": "keyword", "ignore_above": 256 } } },
          "value": { "type": "long" }
        }
     }
 }
}

**Short Description**
**I have two pyspark jobs.** 
a) The first one populates ES with documents and for some documents, **_current_** and **_previous_** attribute values could be null.
b) The second job reads the same documents from the ES and tries to update few attributes using the append method.
The issue i am facing is that while reading from ES in the second job i have specified the above fields as shown below:
dfSource = readFromES(index="test-index", docType="test-doc-type") .option("es.read.field.as.array.include", availability.current,availability.previous") .load()
which results null values in **_"current and previous attributes"_** are converted as [ [],[] ] and while writing back the dataframe to ES it says "scala.MatchError: null" since ES contains nulls and i am trying to write  [ [],[] ]. This is happening only with ES 6.8.3 but not with ES 5.6.3.

### Steps to reproduce
**PySpark Job 1:**
**a) I have defined schema as shown below in PySpark Job:**
nestedSchema = StructType([
StructField('current',ArrayType(
StructType([
StructField('lastUpdateTm',LongType(),nullable=True),
StructField('size',StringType(),nullable=True),
StructField('value',LongType(),nullable=True)
])
),nullable=True),
StructField('previous',ArrayType(
StructType([
StructField('lastUpdateTm',LongType(),nullable=True),
StructField('size',StringType(),nullable=True),
StructField('value',LongType(),nullable=True)
])
),nullable=True)
])

**b) Write to ES:**
udfCreateObject = udf(lambda x,y:[x,y],nestedSchema)

dfOther = dfSource.groupBy('id').agg(collect_list('current').alias('aggrCurrent'),collect_list('previous').alias('aggrPrevious'))

dfTarget = dfSource.withColumn('active',lit(True))
.withColumn('hashKey',concat_ws("-","key-column1","key-column2")) \
.withColumn("availability",udfCreateObject(dfOther.aggrCurrent,dfOther.aggrPrevious))

writeToES(dataToWrite=dfTarget, index="test-index", docType="test-doc-type", mappingID='hashKey') .save()

**c) Sample ES document:**
"_index": "test-index",
"_type": "test-doc-type",
"_source": {
				"hashKey" : "key1",
				"active": true,
				"availability": {
					"current": null,
					"previous": null
				}
			},
_index": "test-index",
"_type": "test-doc-type",
"_source": {		
		"hashKey" : "key2",
		"active": true,
		"availability": {
		"current": [
                        {
                            "lastUpdateTm": 1571702400000,
                            "size": "10",
                            "value": 100
                        },
                     ...
                    ],
                    "previous": [
                        {
                            "lastUpdateTm": 1571702400000,
                            "size": "30",
                            "value": 200
                        },
                      ...
                    ]
	}
}
}

**PySpark Job 2:**
I have another PySpark job which reads Elasticsearch from the above index "test-index", doc type "test-doc-type" and writes it back with updated values.

**a) dfSource = readFromES(index="test-index", docType="test-doc-type") .option("es.read.field.as.array.include", availability.current,availability.previous") .load()**

**b) dfTarget = "Target data frame after transformations"**

**c) Please follow two rows after printing the above dataframe**
+---------+-----------------------------------------------------------------------------------------------------------------------------------+
|hashKey |availability |
+---------+---------------------------------------------------------------------------------------------+
|key1 |[ [], []] |
|key2 |[[[1571702400000,10,100], [1571702400000,20,1000]], [[1571702400000,30,200], [1571702400000,40,1500]]]|
+---------+-------------------------------------------------------------------------------------------------
**d) writeToES(dataToWrite=dfTarget, index="test-index", docType="test-doc-type", mappingID='hashKey').save()**

**Strack trace:**
org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: scala.MatchError: null
        at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:136)
        at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:74)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: scala.MatchError: null
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:74)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:101)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$doWriteSeq$1.apply(DataFrameValueWriter.scala:121)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$doWriteSeq$1.apply(DataFrameValueWriter.scala:120)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.doWriteSeq(DataFrameValueWriter.scala:120)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeArray(DataFrameValueWriter.scala:111)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:102)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
        at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:101)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
        at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
        at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
        at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)
        ... 12 more

ERROR TaskSetManager: Task 164 in stage 417.0 failed 4 times; aborting job

 self.writeToES(dataToWrite=dataToWrite, index=self.config.get('es.index').get('test-index'), docType=self.config.get('es.types').get('test-doc-type'), mappingID='hashKey') \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 734, in save
    self._jwrite.save()
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
Py4JJavaError: An error occurred while calling o374.save.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 164 in stage 417.0 failed 4 times, most recent failure: Lost task 164.3 in stage 417.0 (TID 12146, ip-10-0-102-82.us-west-2.compute.internal, executor 2): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: scala.MatchError: null
        at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:136)
        at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:74)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
        at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: scala.MatchError: null
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:74)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:101)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$doWriteSeq$1.apply(DataFrameValueWriter.scala:121)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$doWriteSeq$1.apply(DataFrameValueWriter.scala:120)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.doWriteSeq(DataFrameValueWriter.scala:120)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeArray(DataFrameValueWriter.scala:111)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:102)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
        at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:101)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
        at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
        at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70)
        at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
        at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
        at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)
        ... 12 more

### Version Info
OS:         :  Amazon Linux
JVM         :  
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
Hadoop/Spark:  
ES-Hadoop   :  
ES          :  6.8.3

**Other details:**
Tried on two AWS EMR versions:
**1)**
EMR Version :emr-5.8.0
Hadoop distribution:Amazon 2.7.3
Applications: Spark 2.2.0, Hive 2.3.0
Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_141)
Python version 2.7.12 (default, Sep  1 2016 22:14:00)
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)

**2)** 
EMR Version : emr-5.22.0
Hadoop distribution:Amazon 2.8.5
Applications:Spark 2.4.0, Hive 2.3.4
Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Python version 2.7.15 (default, Nov 28 2018 22:38:08)
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by masseyke** [comment] 2021-12-07 23:59
Hi @visu0307. Sorry for the extremely long delay. Could you provide a little more information? I'm having trouble reproducing this. Could you post your command to create your mapping (I'm assuming that there are no fields of type [`nested`](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html), but that you're just using nested to refer to how `current` and `previous` are under `availability` in the mapping, right?)? And could you also poste the code snippet behind `readFromES`? For what it's worth, here is what I am doing that is _not_ reproducing the problem:
First I create the index with a mapping like yours:
```
curl -X PUT "localhost:9200/nested-index?pretty" -H 'Content-Type: application/json' -d'
{
   "mappings":{
      "properties":{
         "availability":{
            "type":"object",
            "properties":{
               "current":{
                  "type":"object",
                  "properties":{
                     "lastUpdateTm":{
                        "type":"long"
                     },
                     "size":{
                        "type":"keyword",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "value":{
                        "type":"long"
                     }
                  }
               },
               "previous":{
                  "type":"object",
                  "properties":{
                     "lastUpdateTm":{
                        "type":"long"
                     },
                     "size":{
                        "type":"keyword",
                        "fields":{
                           "keyword":{
                              "type":"keyword",
                              "ignore_above":256
                           }
                        }
                     },
                     "value":{
                        "type":"long"
                     }
                  }
               }
            }
         }
      }
   }
}
'
```
Next I put in a couple of rows:
```
curl -X PUT "localhost:9200/nested-index/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
   "availability":{
      "current":[
         {
            "lastUpdateTm":1571702400000,
            "size":"10",
            "value":100
         }
      ],
      "previous":[
         {
            "lastUpdateTm":1571702400000,
            "size":"30",
            "value":200
         }
      ]
   }
}
'
curl -X PUT "localhost:9200/nested-index/_doc/2?pretty" -H 'Content-Type: application/json' -d'
{
  "availability": {
    "current" : null,
    "previous" : null
  }
}
'
```
Then from spark shell I do 
```
from pyspark.sql import *
reader = spark.read.format("org.elasticsearch.spark.sql")
df_elastic = reader .option("es.read.field.as.array.include", "availability.current,availability.previous").load("nested-index")
df_elastic.show()
+--------------------+                                                          
|        availability|
+--------------------+
|    {[null], [null]}|
|{[{1571702400000,...|
+--------------------+
```
It's possible that this has been fixed in the last couple of years -- I tested this using a very recent snapshot.

**Comment by masseyke** [comment] 2022-02-02 20:01
I'm closing this one since I can't reproduce it. Please reopen it if you can provide steps to reproduce it though.

**Closed by masseyke** 2022-02-02 20:01 UTC
Labels: bug, :Spark, :Serialization

**Comment by Kimahriman** [comment] 2023-07-27 15:01
I think this is the same error we are encountering. The bug happens during writes, when you have an array of structs, and one of the elements of the array is null. There is no check for a null value in that path. Arrays of primitives would get caught here: https://github.com/elastic/elasticsearch-hadoop/blob/main/spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala#L250-L252

But there is no such path to catch the same thing for structs. Null structs can only be handled correctly if they are a direct child of another struct here: https://github.com/elastic/elasticsearch-hadoop/blob/main/spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala#L96-L105
