### ISSUE TITLE
Store Tuple as object with Pig in Elasticsearch

### ISSUE THREAD

**Issue by florentvaldelievre** [elastic/elasticsearch-hadoop#746] opened 2016-04-14 14:31 UTC
Hello,

I am not sure if its a bug or working as design but I would prefer to have a confirmation from you. I asked the question on stackoverflow but not answer so far.

I am having an issue with the format EsStorage store tuples into Elasticsearch.
Let's take a concrete example:

```
X: {id: chararray,score: long,answers: {(id: chararray,score: long)}}
(4,385,{(7,287),(7263,48)})
```
I am using the following ESStorage configuration:

```
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage (
              'es.http.timeout= 5m',
              'es.index.auto.create = true',
              'es.mapping.pig.tuple.use.field.names = true',
              'es.nodes = $es_nodes',
              'es.mapping.id = id'
           );
```
And I store my tuples like this:

STORE X INTO '$es_index_name/$es_index_type' USING EsStorage;
The result is the following:
```

     {
        "_index": "stackoverflow_test3",
        "_type": "post",
        "_id": "4",
        "_score": 1,
        "_source": {
           "id": "4",
           "score": 385,
           "answers": [
              [
                 {
                    "id": "7",
                    "score": 287
                 }
              ],
              [
                 {
                    "id": "7263",
                    "score": 48
                 }
              ]
          }
    }
```
I'am expecting to have something like this:

   ```
  {
        "_index": "stackoverflow_test3",
        "_type": "post",
        "_id": "4",
        "_score": 1,
        "_source": {
           "id": "4",
           "score": 385,
           "answers": [
                 {
                    "id": "7",
                    "score": 287
                 },
                 {
                    "id": "7263",
                    "score": 48
                 }
             ]
          }
    }
```

As far as i can see in the [documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/pig.html#tuple-names) 

(foo: (nr:int, name:chararray)) is converted to {"foo":[{"nr":1, "name":"kimchy"]} which is not what I was expecting

Any hint would be greatly appreciated.

**Comment by costin** [comment] 2016-04-14 17:09
>  I asked the question on stackoverflow but not answer so far.

Sorry I don't follow Stackoverflow, only the dedicated [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) (the one mentioned when you raised this issue).

Based on your ticket it looks like a bug - do you have a small sample at hand (to make sure there are other entries that affect the mapping)?
Info on the Pig version used, ES and ES-Hadoop (the latest) is critical.

Cheers,

**Comment by florentvaldelievre** [comment] 2016-04-15 08:49
Sure thing, you will find below a straight forward example ready to be executed

*Pig*
Apache Pig version 0.15.0.2.3.4.0-3485 (rexported) 
compiled Dec 16 2015, 04:30:33

*Elasticsearch*
"version":
"number": "1.7.1"
"build_hash": "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19"
"build_timestamp": "2015-07-29T09:54:16Z"
"build_snapshot": false
"lucene_version": "4.10.4"

*ES-Hadoop*
I have tried with both version 2.2.0 and 2.3.0, same result:
2.2.0: http://central.maven.org/maven2/org/elasticsearch/elasticsearch-hadoop/2.2.0/elasticsearch-hadoop-2.2.0.jar
2.3.0: http://central.maven.org/maven2/org/elasticsearch/elasticsearch-hadoop/2.3.0/elasticsearch-hadoop-2.3.0.jar

We will use the following data stored in test.txt in the HDFS:

```
4,7,287
4,7263,48
```

Pig script:
```
REGISTER /usr/hdp/current/pig-client/lib/elasticsearch-hadoop-2.3.0.jar
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage (	
	              'es.index.auto.create = true',
	              'es.mapping.pig.tuple.use.field.names = true',
	              'es.nodes = 10.100.50.100'
               );
answers = LOAD 'test.txt' USING PigStorage(',') AS (id:int, parentId:int, score:int);
grouped = GROUP answers BY id;
STORE grouped INTO 'es_storage/test' USING EsStorage;
```

The result in Elasticsearch is the following:

```
"_source": {
               "group": 4,
               "answers": [
                  [
                     {
                        "id": 4,
                        "parentId": 7263,
                        "score": 48
                     }
                  ],
                  [
                     {
                        "id": 4,
                        "parentId": 7,
                        "score": 287
                     }
                  ]
               ]
            }
```

I was expecting the following:

           ```
 "_source": {
               "group": 4,
               "answers": [
                  {
                        "id": 4,
                        "parentId": 7263,
                        "score": 48
                  },
                  {
                     "id": 4,
                     "parentId": 7,
                     "score": 287
                  } 
               ]
            }

```

**Comment by ebuildy** [comment] 2016-04-15 17:05
Got this problem too, I don't find a good tutorial that could explain how to use ES with complex PIG data structures ;/ 

Is it something supported by this plugin yet?

**Comment by florentvaldelievre** [comment] 2016-04-17 18:23
@costin, did you have time to have a closer look?

**Comment by costin** [comment] 2016-05-25 16:29
Hi folks,

Sorry for talking so long to reply.
Let me try and clarify how tuples are handled. Thanks to @florentvaldelievre  detailed issue (cheers!) one can have this structure:
```
------------------------------------------------------------
| answers     | id:int    | parentId:int    | score:int    | 
------------------------------------------------------------
|             | 4         | 7               | 287          | 
|             | 4         | 7263            | 48           | 
------------------------------------------------------------
--------------------------------------------------------------------------------------------------
| grouped     | group:int    | answers:bag{:tuple(id:int,parentId:int,score:int)}                | 
--------------------------------------------------------------------------------------------------
|             | 4            | {(4, 7, 287), (4, 7263, 48)}                                      | 
--------------------------------------------------------------------------------------------------
```

Let's start inward -> outward, first with the tuple namely: `tuple(id:int,parentId:int,score:int)`

To quote the [docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/pig.html#tuple-names) 
> Tuples are defined as “ordered sets of fields” (e.g. (19,2)) however structurally they are shaped as ordered maps since each field has a name, which may be defined or not (e.g. (field:19, another:2)). 

Notice ordered set of fields. In other words a tuple can have _duplicates_ and further more is _ordered_. 
Further more, a tuple can be named but many times it is not. The names are important since if names are used ES-Hadoop can use a JSON object. However if names are not used, then using such an object is not possible (arbitrary names could be used but this simply adds noise).
However there is a subtle aspect here - JSON objects are *NOT* ordered. When using a named tuple, the order is reconstructed by doing name lookups (from the Pig schema). However without the names, the order is lost and cannot be inferred. Which means the data is not read the same way it is written.

The only complex structure that preserves ordering is a JSON array - hence why a tuple is always saved as an array. 

Coming back to the tuple, an array `[ ..]` structure is created. If names are used inside the array, for each tuple instance an object is being created: `[ { ... } ]`. The enclosing `bag` is a list basically a JSON array which leads to the `[ [ { ... } ] ]` structure.

Does this clarify the situation?

**Comment by costin** [comment] 2016-05-30 16:02
Folks I'm happy to continue the discussion but as I've explained above, this is not a bug and as such, I'm closing the issue...

**Closed by costin** 2016-05-30 16:02 UTC
Labels: :Pig, invalid, question, v2.3.3, v5.0.0-alpha3
