### ISSUE TITLE
many duplicate documents returned when using es-hadoop to query compared to curl

### ISSUE THREAD

**Issue by mashuai191** [elastic/elasticsearch-hadoop#1486] opened 2020-06-04 04:23 UTC
### What kind an issue is this?

-  Bug report. 

### Issue description

Description: es-hadoop return many duplicated documents when i use range filter on timestamp.

### Steps to reproduce

Code:

1. when i use following shell to get the curl result, i can get only 2 hits.

```
curl -u username:password -H 'content-Type:application/json' -XGET my_ip:port/filer-*/_search?pretty -d'
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "event.dataset": "auditd.log"
          }
        },
        {
          "term": {
            "auditd.log.from": "smb"
          }
        },
        {
            "range" : {
                "auditd.log.timestamp" : {
                    "gte" : "1591090993",
                    "lt" :  "1591092573"
                }
            }
        },
        {
          "bool": {
            "minimum_should_match": "1",
            "should": [
              {
                "term": {
                  "auditd.log.action": "create"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    {
      "auditd.log.timestamp": {
        "order": "desc"
      }
    }
  ]
}'
```
2. but when i use the same query in es-hadoop to do the same thing, it returned 68 hits, with many documents duplicated. Then i run dropDuplicates() can remove all the duplicated documents to get 2 remaining documents which is same as the curl result.

```

import org.apache.spark.sql.types._


var q = """
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "event.dataset": "auditd.log"
          }
        },
        {
          "term": {
            "auditd.log.from": "smb"
          }
        },
        {
            "range" : {
                "auditd.log.timestamp" : {
                    "gte" : "1591090993",
                    "lt" :  "1591092573"
                }
            }
        },
        {
          "bool": {
            "minimum_should_match": "1",
            "should": [
              {
                "term": {
                  "auditd.log.action": "create"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    {
      "auditd.log.timestamp": {
        "order": "desc"
      }
    }
  ]
}"""


var my_index = "filer-*"

val options = Map("es.nodes" -> "my_ip", 
                  "es.port" -> "port",
                  "pushdown" -> "true",
                  "es.nodes.wan.only" -> "true",
                  "es.nodes.discovery" -> "false",
                  "es.net.http.auth.user" -> "username",
                  "es.net.http.auth.pass" -> "password",
                  "es.query" -> q,
                  "es.read.field.include" -> "@timestamp, auditd.*",
                  "es.scroll.size" -> "1000",
                  "double.filtering" -> "true"
                  )

// Spark 1.4 style
val spark14DF = sqlContext.read.format("es")
                        .options(options) 
                        .load(my_index)
                        
                        
spark14DF.count()   // this gives 68     
```

Strack trace: no error logs shown, seems everything goes well.

### Version Info

OS:         :  Ubuntu 16.04.6 LTS 
JVM         :  openjdk version "1.8.0_242"
Hadoop/Spark:  spark 2.4.6-snapshot
ES-Hadoop   :  7.6.0
ES          :  6.5.4

**Comment by schahaha** [comment] 2020-06-18 05:13
If a reduce task fails, and then try again, is this part of the data written repeatedly?I feel like this will also lead to duplication.

**Comment by mashuai191** [comment] 2020-06-18 07:44
@schahaha thanks for reply. I think even there is duplicate data, curl command should return those because they have diffent id in ES. so issue here is curl and ES-hadoop give diffrent result with the same query.

**Comment by jbaiera** [comment] 2020-07-14 17:17
A couple of questions here:

1) When you say duplicates, do you mean documents that should not have matched the query were returned, or do you mean multiple copies of the same document were returned?

2) is this reproducible in a consistent manner? Was there anything happening on the cluster when this occurred? Were there any task level failures when this happened?

3) Can you describe how your index is configured, and how the data is indexed within it?

**Comment by jbaiera** [comment] 2020-09-18 16:50
Closing since no further feedback was received.

**Closed by jbaiera** 2020-09-18 16:50 UTC
Labels: feedback-requested
