### ISSUE TITLE
Document Count in ES Different from Number of Entries Pushed

### ISSUE THREAD

**Issue by swatisaini** [elastic/elasticsearch-hadoop#1086] opened 2017-12-20 11:22 UTC
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by swatisaini** [comment] 2017-12-20 11:25
There is mismatch found in document count while reading data from elasticsearch index using  pyspark code. 
Actual document count in elasticsearch is 991121(1.08 GB)  but when we read data into spark, at every attempt it keep changing. 
Number of shards - 5
replica - 0
following is the observation 
 
1 st try 991121
2nd try 991147 
3rd try 991095 
Architecture version info 
 spark version is 2.0.2
scala - 2.11
python 2.7 
elasticsearch 5.1.1
elasticsearch-spark connector-  20_2.11-5.1.1

**Comment by jbaiera** [comment] 2018-01-09 16:19
It looks like the counts vary by 26 in either direction. That stands out to me a little bit. Are you able to identify the 26 records that are appearing/disappearing between runs?

**Comment by swatisaini** [comment] 2018-01-11 07:38
Hi James,

This is just one scenario we have tested with different data sets also, the
count can vary one to thousands in another datasets.
I found this issue, it's because of number of partitions when i read it
with minimal number of partitions  then the count is consistent.  But I
didn't get why it's happening.

Thanks and regards,

Swati Saini
Bachelor of Technology
IIT Kharagpur, 2016
+91 70766 07599 | LinkedIn
<https://in.linkedin.com/pub/swati-saini/59/734/b89>

**Comment by jimczi** [comment] 2018-01-11 13:22
We fixed a bug in es 5.3.1 that could explain the discrepancies that you're seeing. How many elasticsearch nodes do you have in your cluster ? Can you try to upgrade the elasticsearch cluster to 5.6 and see if the issue reproduces ?

**Comment by swatisaini** [comment] 2018-01-12 10:41
Hi Jimczi, 
Thanks for the solution we have 3 nodes in a cluster.  Will try to upgrade the elasticsearch and see if the problem is solved.

**Comment by jbaiera** [comment] 2018-02-14 20:46
I'm going to go ahead and close this out unless there's any further issues. I assume that the bug mentioned above was the leading cause. Let us know if we should re-open this issue.

**Closed by jbaiera** 2018-02-14 20:46 UTC
Labels: :Spark, bug, feedback-requested
