### ISSUE TITLE
Spark `--packages` problem regarding dependencies

### ISSUE THREAD

**Issue by brkyvz** [elastic/elasticsearch-hadoop#447] opened 2015-05-05 17:07 UTC
Hi @costin ,

I just wanted to notify you that you received a message on Spark Packages regarding this package. 
http://spark-packages.org/package/elasticsearch/elasticsearch-hadoop

The problem is regarding the dependency `cascading:cascading-local` not existing on Maven Central, and the repository where it can be found not being in the pom.
Could you please help out?

Thanks,
Burak

**Comment by costin** [comment] 2015-05-05 18:09
Thanks for the heads up, I'll look into it.

**Comment by NoxWings** [comment] 2015-05-13 13:44
+1

For people looking for a temporal workaround:
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by costin** [comment] 2015-05-13 17:37
@NoxWings Can you clarify what the workaround is? All of the [POM](https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-hadoop/2.1.0.Beta3/elasticsearch-hadoop-2.1.0.Beta3.pom) dependencies are already marked as `optional` or `provided`.

**Comment by brkyvz** [comment] 2015-05-13 17:45
Hmmm, wondering if this can be fixed on the Spark side. Currently the `--packages` option tries to download everything, even jars defined with the scope `test`. Didn't realize they were provided as optional. I'll look into it on the Spark side.

**Comment by NoxWings** [comment] 2015-05-14 09:07
@costin I've had to manually add the exclusion on the cascading dependencies.
Using 2.1.0.Beta4 version.

**Comment by costin** [comment] 2015-05-14 10:23
@NoxWings According to the maven docs, an optional dependency should not be downloaded. Now, I expect that Maven still wants to get the POM for whatever reason which causes the problems you are seeing.
Note that you can use `elasticsearch-spark` jar directly; see the reference documentation - in case of Spark packages this is not an option since it requires the project to have the same name in Github which is not the case.
By using the `elas

**Comment by costin** [comment] 2015-05-20 08:53
@brkyvz @NoxWings There are two fixes for this issue.
The easiest one (which I recommend) is using the dedicated spark jar:
> $SPARK_HOME/bin/spark-shell --packages org.elasticsearch:elasticsearch-spark_2.10:2.1.0.Beta4

Has minimal dependencies and allows you to specify the Scala version (2.10 vs 2.11).

The `elasticsearch-hadoop` jar POM is fixed in master so running
> $SPARK_HOME/bin/spark-shell --packages org.elasticsearch:elasticsearch-hadoop:2.1.0.BUILD-SNAPSHOT
should work.

For 2.1.0.Beta3 and Beta4, the customer cascading repository needs to be specified by adding the `--repository http://conjars.org/repo` to the command line.

I've contacted the site owners to try and update the project description with this information (currently it's in this issue and also in the site comments).

Cheers,

**Comment by NoxWings** [comment] 2015-05-20 09:56
@costin
I'll be using that dependency then, I didn't noticed about the elastic search spark artifact before. Thank you.

**Comment by costin** [comment] 2015-06-25 19:48
@brkyvz Sent you an email regarding updating es-hadoop inside Spark packages. Cheers!

**Comment by costin** [comment] 2015-06-29 20:37
Thanks to @brkyvz, the packages on Spark package have been refreshed as one can see [here](http://spark-packages.org/package/elastic/elasticsearch-hadoop).

Cheers,

**Closed by costin** 2015-06-29 20:37 UTC
Labels: reviewed, spark, v2.1.1, v2.2.0.m1

**Comment by hyunjun** [comment] 2015-12-15 07:41
@costin Could you let me know which is wrong?
```
name := "..."

version := "..."

scalaVersion := "2.10.6"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "1.5.2",
  "org.apache.commons" % "commons-lang3" % "3.4",
  //"org.elasticsearch" % "elasticsearch-spark_2.10" % "2.1.2"
  "org.elasticsearch" % "elasticsearch-hadoop" % "2.1.2"
)

//resolvers += "conjars" at "http://conjars.org/repo"
```

When running `sbt package`, I got `[error] (*:update) sbt.ResolveException: unresolved dependency: cascading#cascading-local;2.6.3: not found`
I changed the version of elasticsearch-hadoop, and the resover, however it's not working either.

Also, I changed elasticsearch-hadoop to elasticsear-spark, then `sbt package` works, however `Caused by: java.lang.ClassNotFoundException: org.elasticsearch.spark.package` occurs when running
