### ISSUE TITLE
EsInputFormat is not thread safe in pyshark.

### ISSUE THREAD

**Issue by hukang88888** [elastic/elasticsearch-hadoop#1465] opened 2020-04-24 07:30 UTC
Bug

### Issue description

Use es in Pyspark is not thread safe when python code only consume the first document. 
You will see below msg when two thread use the same socket.

BasePythonRunner$WriterThread is write es data to python-daemon worker process.
Because the python only consume the first item, it quit soon while the WriterThread still fetch data and write to it. The task is finished, the task executor thread will close scroll.  In this case,  two threads will use the same socket to send http request.

Attach the fix base on v7.6.2:
[diff.txt](https://github.com/elastic/elasticsearch-hadoop/files/4527327/diff.txt)

```
WARN  20/04/24 07:04:15.551 [Executor task launch worker for task 2:org.apache.commons.httpclient.SimpleHttpConnectionManager]: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.
```

### Steps to reproduce

Code:

```
        raw_rdd = spark.newAPIHadoopRDD(
            inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
            keyClass="org.apache.hadoop.io.NullWritable",
            valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
            conf={
                "es.nodes": self.config.get("es.nodes"),
                "es.port": self.config.get("es.port"),
                "es.resource": "XXX",
                "es.query": "XXX",
                "es.nodes.wan.only": self.config.get("es.nodes.wan.only"),
                "es.read.source.filter": ''
            })
        while True:
            print('take1')
            raw_rdd.take(1)
```

Strack trace:

```
java.lang.NullPointerException
	at org.elasticsearch.hadoop.rest.RestClient.scroll(RestClient.java:498)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:329)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:115)
	at org.elasticsearch.hadoop.mr.EsInputFormat$EsInputRecordReader.next(EsInputFormat.java:255)
	at org.elasticsearch.hadoop.mr.EsInputFormat$EsInputRecordReader.nextKeyValue(EsInputFormat.java:189)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:230)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:156)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:148)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:148)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:224)
	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:561)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$anonfun$run$1.apply(PythonRunner.scala:346)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1945)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:195)
``` 

```
WARN  20/04/22 02:39:19 [Executor task launch worker for task 1:org.apache.spark.rdd.NewHadoopRDD]: Exception in RecordReader.close()
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[10.8.2.229:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:160)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:432)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:428)
	at org.elasticsearch.hadoop.rest.RestClient.executeNotFoundAllowed(RestClient.java:440)
	at org.elasticsearch.hadoop.rest.RestClient.deleteScroll(RestClient.java:515)
	at org.elasticsearch.hadoop.rest.ScrollQuery.close(ScrollQuery.java:78)
	at org.elasticsearch.hadoop.mr.EsInputFormat$EsInputRecordReader.close(EsInputFormat.java:219)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.org$apache$spark$rdd$NewHadoopRDD$$anon$$close(NewHadoopRDD.scala:272)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1$$anonfun$3.apply(NewHadoopRDD.scala:221)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1$$anonfun$3.apply(NewHadoopRDD.scala:217)
	at org.apache.spark.TaskContext$$anon$1.onTaskCompletion(TaskContext.scala:131)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:117)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:117)
	at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:130)
	at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:128)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:128)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:116)
	at org.apache.spark.scheduler.Task.run(Task.scala:139)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Version Info

OS:         :  Ubuntu 18.04.3 LTS
JVM         :  openjdk version "1.8.0_252"
Hadoop/Spark:  2.4.4
ES-Hadoop   :  7.3.2,  got same error on latest version 7.6.2 
ES          :  7.3.2

**Comment by masseyke** [comment] 2021-12-03 21:04
Hi @hukang88888 I have tired using your python to reproduce this in spark 3.1.2 but I have not been able to. It sounds to me like a spark bug, and I'm wondering if they have fixed it. I will try to get set up on 2.4.4 to try to reproduce it. Is there anything else required to reproduce it? I just created an index and insert 1000 small documents, then let the code above run for a few minutes. I didn't see any errors.

**Comment by masseyke** [comment] 2021-12-03 22:47
I have also been unable to reproduce this on spark 2.4.4 with elasticsearch-spark-20_2.11-7.6.2.jar using an index with 9500 documents. Any other tips on reproducing this?

**Comment by masseyke** [comment] 2022-01-05 15:36
I'm going to close this since I can't reproduce it. Please reopen it if you're able to reproduce it reliably.

**Closed by masseyke** 2022-01-05 15:36 UTC
Labels: bug, :Spark, :Core
