### ISSUE TITLE
support for push down predicates

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#13] opened 2013-04-01 16:27 UTC
Ideally, where possible, we should try to convert the hive operations to ES queries - to minimize IO but also the work done on the Hive side.

**Comment by cyndsl** [comment] 2015-12-29 11:31
@costin 
I use v2.2.0.Beta1, except for es.query, is there any method to push down predicates in hiveql

**Comment by jbaiera** [comment] 2018-02-05 17:47
Duplicate of #4

**Closed by jbaiera** 2018-02-05 17:47 UTC
Labels: :Hive, :Pig, feature, stalled
