### ISSUE TITLE
Unhandled Exception in org.elasticsearch.spark.rdd.EsRDDWriter.write, and rdd wouldn't stop.

### ISSUE THREAD

**Issue by willard-kali** [elastic/elasticsearch-hadoop#719] opened 2016-03-12 09:39 UTC
### What kind an issue is this?

Bug report.

### Issue description

  I deployed a kafka to Spark-Streaming then ElasticSearch system.The system has continued to receive data from kafka, and the data stream is a uniform.
  In this system during normal operation , I restarted all the ElasticSearch nodes.And then found the indexing process delay in growth , by querying the data in the ElasticSearch.
  In Yarn batch management interface can see the task appeared exception, but the batch is still processing state , and this state continues for several days. And under normal circumstances, it should be completed within a few seconds.
  These tasks really throw an exception , but it does not seem to stop and release resources in my view , which is not appropriate approach.
  I would like to confirm whether this is a bug, and is there a solution to stop these abnormal tasks and release resources?

### Sample Configuration / Code

My Code:

```
import org.elasticsearch.spark._

stream.foreachRDD( rdd=>
      {
        val ep = esPath + getIndexName("") + "/meta"
        rdd.saveToEs(ep)
      }
)
```

Exception Messages:

> Job aborted due to stage failure: Task 2 in stage 123.0 failed 4 times, most recent failure: Lost task 2.3 in stage 123.0 (TID 12345, hostname): org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [] failed; server[xxx.xxx.xxx.xxx:9200] returned [503|Service Unavailable:]
> 	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:467)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:425)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:403)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:407)
> 	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:114)
> 	at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:553)
> 	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:177)
> 	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:379)
> 	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
> 	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
> 	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
>         ``` 

and other:

> Job aborted due to stage failure: Task 0 in stage 33.0 failed 4 times, most recent failure: Lost task 0.3 in stage 33.0 (TID 4171, hostname): org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[xxx.xxx.xx.xx:9200]] 
> 	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:423)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:403)
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:407)
> 	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:114)
> 	at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:553)
> 	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:177)
> 	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:379)
> 	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
> 	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
> 	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
>        ...

and so on.

#suspected bug location

> elasticsearch-hadoop-master\spark\core\main\scala\org\elasticsearch\spark\rdd\EsRDDWriter.scala

line 41:
`val writer = RestService.createWriter(settings, taskContext.partitionId, -1, log)`

Is there no try-catch for handling exceptions?

### Version Info

Java        :  1.8.0_51
Hadoop/Spark:  spark-streaming-xxx_2.10-1.3.0
ES-Hadoop   :  elasticsearch-spark_2.10-2.2.0
ES          :  elasticsearch-1.7.1

**Comment by costin** [comment] 2016-03-22 13:29
Errors that can be handled are caught, those that cannot are bubbling up.
In your case it looks the issue is the usage of Spark Streaming - that is, for every micro-batch you end up trying to save the RDD which spawns a job.
However it looks like ES is falling behind and not being responsive any more and thus every call to it ends up timing out or with a 503, even for basic things such as discovering the version.
Since your stream keeps on going:
```
stream.foreachRDD( rdd=>
      {
        val ep = esPath + getIndexName("") + "/meta"
        rdd.saveToEs(ep)
      }
```
each `rdd.saveToEs` keeps throwing exceptions yet keeps on running.

> These tasks really throw an exception , but it does not seem to stop and release resources in my view , which is not appropriate approach.

What resources in ES-Hadoop are you referring to? ES-Hadoop cannot even initialize - in fact it hasn't even allocated any resources...

**Comment by costin** [comment] 2016-03-22 13:31
One thing to add, the `DStream` support could be improved since each rdd call ends up creating a full blown job which is expensive (as mentioned [here](http://spark.apache.org/docs/latest/streaming-programming-guide.html#design-patterns-for-using-foreachrdd)).

Since Spark 2.0 should be released soon, I'm aiming for that to revise the streaming support.

**Comment by costin** [comment] 2016-05-03 10:40
Since there hasn't been any update on this issue, I'm closing it down. If the issue still persists, please open a new one (and potentially link this as well).

Cheers

**Closed by costin** 2016-05-03 10:40 UTC
Labels: question, spark, v2.3.1
