### ISSUE TITLE
select count(*) from  <table>; fails in hive

### ISSUE THREAD

**Issue by mohantnr** [elastic/elasticsearch-hadoop#787] opened 2016-06-08 09:56 UTC
### What kind an issue is this?

Querying hive to elasticsearch
- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.  
  The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
  Often a solution already exists! Don’t send pull requests to implement new features without 
  first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
select count(1) from msbilogs; 
INFO  : Number of reduce tasks determined at compile time: 1 INFO  : In order to change the average load for a reducer (in bytes):
INFO  :   set hive.exec.reducers.bytes.per.reducer=<number>
INFO  : In order to limit the maximum number of reducers:
INFO  :   set hive.exec.reducers.max=<number>
INFO  : In order to set a constant number of reducers:
INFO  :   set mapreduce.job.reduces=<number>
INFO  : Cleaning up the staging area /user/hive/.staging/job_1465210153149_0065
ERROR : Job Submission failed with exception 'java.lang.NullPointerException(null)'
java.lang.NullPointerException
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at org.elasticsearch.hadoop.mr.EsInputFormat$ShardInputSplit.write(EsInputFormat.java:108)
        at org.elasticsearch.hadoop.hive.EsHiveInputFormat$EsHiveSplit.write(EsHiveInputFormat.java:77)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.write(HiveInputFormat.java:177)
        at org.apache.hadoop.mapreduce.split.JobSplitWriter.writeOldSplits(JobSplitWriter.java:164)
        at org.apache.hadoop.mapreduce.split.JobSplitWriter.createSplitFiles(JobSplitWriter.java:92)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeOldSplits(JobSubmitter.java:353)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:323)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:199)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
        at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:564)
        at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:559)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:559)
        at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:550)
        at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:429)
        at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:137)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:160)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:88)
        at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1636)
        at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1396)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1181)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1047)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1042)
        at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:144)
        at org.apache.hive.service.cli.operation.SQLOperation.access$100(SQLOperation.java:69)
        at org.apache.hive.service.cli.operation.SQLOperation$1$1.run(SQLOperation.java:196)
        at java.security.AccessController.doPrivileged(Native Method)
     ... (truncated, see original email for full text) 
### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
```
### Version Info

OS:         :  CENTOS 6.5
JVM         : java version "1.7.0_67"

Hadoop/Spark:  CDH 5.5.x  hive-common-1.1.0-cdh5.5.1.jar
ES-Hadoop   : elasticsearch-hadoop-2.3.2.jar
ES          :  elasticsearch-2.3.3-1.noarch

**Comment by costin** [comment] 2016-06-08 16:21
Can you please pay attention to the template and fill it properly? You are not describing what you are trying to and what triggers the failure - please post your Hive table declaration and the snippet of script that triggers the error.
The stracktrace is useful but not fully relevant (not to mention it is incomplete
>... (truncated, see original email for full text) 
?
)

**Comment by AmolGaitondeES** [comment] 2016-06-09 03:51
More details in the template format for the above issue ...
### What kind an issue is this?

- [Yes] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 


### Issue description
SELECT count(1) from an external table in hive which accesses Elastics search index fails
Description
SELECT count(*) from an external table in hive which accesses Elastics search index fails with the error message provided below. However when we do a select * from the external table it works fine,
### Steps to reproduce
Code:

mapping of the elastic search index 
  "msftbi" : {
    "mappings" : {
      "MSFTBI" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "@version" : {
            "type" : "string"
          },
          "Area" : {
            "type" : "string"
          },
          "Category" : {
            "type" : "string"
          },
          "Correlation" : {
            "type" : "string"
          },
          "EventID" : {
            "type" : "string"
          },
          "Level" : {
            "type" : "string"
          },
          "Message" : {
            "type" : "string"
          },
          "Process" : {
            "type" : "string"
          },
          "TID" : {
            "type" : "string"
          },
          "Timestamp" : {
            "type" : "string"
          },
          "host" : {
            "type" : "string"
          },
          "message" : {
            "type" : "string"
          },
          "path" : {
            "type" : "string"
          },
          "tags" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          }
        }
      }
    }
  }
CREATE EXTERNAL TABLE msbilogs (
area STRING,
eventid STRING, level STRING)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.nodes' = 'localhost', 'es.port' = '9201', 'es.nodes.client.only' = 'true', 'es.resource' = 'msft/msbi',
              'es.index.auto.create' = 'false'); 

BELOW IS THE SQL QUERY WHICH FAILS
select count(1) from msbilogs;

Error messages
INFO : Number of reduce tasks determined at compile time: 1 INFO : In order to change the average load for a reducer (in bytes):
INFO : set hive.exec.reducers.bytes.per.reducer=
INFO : In order to limit the maximum number of reducers:
INFO : set hive.exec.reducers.max=
INFO : In order to set a constant number of reducers:
INFO : set mapreduce.job.reduces=
INFO : Cleaning up the staging area /user/hive/.staging/job_1465210153149_0065
ERROR : Job Submission failed with exception 'java.lang.NullPointerException(null)'
java.lang.NullPointerException
at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
at org.elasticsearch.hadoop.mr.EsInputFormat$ShardInputSplit.write(EsInputFormat.java:108)
at org.elasticsearch.hadoop.hive.EsHiveInputFormat$EsHiveSplit.write(EsHiveInputFormat.java:77)
at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.write(HiveInputFormat.java:177)
at org.apache.hadoop.mapreduce.split.JobSplitWriter.writeOldSplits(JobSplitWriter.java:164)
at org.apache.hadoop.mapreduce.split.JobSplitWriter.createSplitFiles(JobSplitWriter.java:92)
at org.apache.hadoop.mapreduce.JobSubmitter.writeOldSplits(JobSubmitter.java:353)
at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:323)
at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:199)
at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:564)
at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:559)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:559)
at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:550)
at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:429)
at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:137)
at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:160)
at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:88)
at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1636)
at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1396)
at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1181)
at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1047)
at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1042)
at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:144)
at org.apache.hive.service.cli.operation.SQLOperation.access$100(SQLOperation.java:69)
at org.apache.hive.service.cli.operation.SQLOperation$1$1.run(SQLOperation.java:196)
at java.security.AccessController.doPrivileged(Native Method)
```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS: : CENTOS 6.5
JVM : java version "1.7.0_67"
Hadoop/Spark: CDH 5.5.x hive-common-1.1.0-cdh5.5.1.jar
ES-Hadoop : elasticsearch-hadoop-2.3.2.jar
ES : elasticsearch-2.3.3-1.noarch


Please let us know if you need additional info.

**Comment by jbaiera** [comment] 2016-06-20 16:17
I'm having a hard time reproducing the issue. How many Elasticsearch nodes are you running locally? Are any of them configured to be client only nodes? According to the stack trace and the provided jar version, it looks like for some reason it's trying to serialize a null ip address for the input split.

I ran a test with one node (non client) and recieved a reasonable error indicating that there were no client nodes to connect to. I spun up a second node locally with `node.master=false` and `node.data=false`, which allowed the query to execute successfully. Neither test produced the null pointer exception.

Could you run the following curl command against your local instance and post the result? `curl -XGET localhost:9201/_nodes/http`

**Comment by AmolGaitondeES** [comment] 2016-06-21 02:46
**Below is the requested information**
`curl -XGET localhost:9201/_nodes/http
{"cluster_name":"ELK-POC","nodes":{"T4MTMNa-SomRi3TvaTlmZA":{"name":"hdfc02dn01","transport_address":"10.64.89.13:9301","host":"10.64.89.13","ip":"10.64.89.13","version":"2.3.3","build":"218bdf1","attributes":{"master":"false"}},"O6fgYzcWT3i_sS9cNlEI3A":{"name":"hdfc02dn04","transport_address":"10.64.89.38:9301","host":"10.64.89.38","ip":"10.64.89.38","version":"2.3.3","build":"218bdf1","attributes":{"master":"false"}},"dsLvGrGORKSY0UpuVxG04A":{"name":"hdfc02dn02","transport_address":"10.64.89.32:9301","host":"10.64.89.32","ip":"10.64.89.32","version":"2.3.3","build":"218bdf1","attributes":{"master":"false"}},"aB-qMOTpSn6B8q2i2Wfuig":{"name":"hdfc02nn01","transport_address":"10.64.89.190:9301","host":"10.64.89.190","ip":"10.64.89.190","version":"2.3.3","build":"218bdf1","attributes":{"data":"false","master":"true"}},"9s7aw6tuR1en6KLIzIuOqw":{"name":"hdfc02nn02","transport_address":"10.64.89.191:9301","host":"10.64.89.191","ip":"10.64.89.191","version":"2.3.3","build":"218bdf1","attributes":{"data":"false","master":"true"}},"yEsMdxifSQqhm5dk7_cBgQ":{"name":"hdfc02gw01","transport_address":"10.64.89.189:9301","host":"10.64.89.189","ip":"10.64.89.189","version":"2.3.3","build":"218bdf1","http_address":"127.0.0.1:9201","attributes":{"data":"false","master":"false"},"http":{"bound_address":["127.0.0.1:9201"],"publish_address":"127.0.0.1:9201","max_content_length_in_bytes":104857600}},"o7tn3vIfQpuIjHVEohXSbA":{"name":"hdfc02dn03","transport_address":"10.64.89.37:9301","host":"10.64.89.37","ip":"10.64.89.37","version":"2.3.3","build":"218bdf1","attributes":{"master":"true"}}}}`

**Comment by jbaiera** [comment] 2016-06-21 14:46
That seems like everything is in the right place... Could you [turn on trace level logging](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/logging.html) for the elasticsearch-hadoop packages and post the logs here? Thanks.

**Comment by jbaiera** [comment] 2017-06-07 20:41
Closing this as there has been no further feedback.

**Closed by jbaiera** 2017-06-07 20:41 UTC
Labels: :Hive, question
