### ISSUE TITLE
elasticsearch-hadoop doesn't work with PySpark

### ISSUE THREAD

**Issue by iirekm** [elastic/elasticsearch-hadoop#2113] opened 2023-07-27 14:08 UTC
```python
from pyspark.sql import SparkSession

spark = SparkSession.builder\
    .config('spark.jars.packages', 'org.elasticsearch:elasticsearch-hadoop:8.4.0')\
    .config("es.nodes", "elasticsearch-main.default")\
    .getOrCreate()
df = spark.read.format("org.elasticsearch.spark.sql").load("index/type")
```

`NoClassDefFoundError: scala/Product$class`

Other popular Spark/Hadoop extensions don't have such problems, because they provide Maven artifacts for multiple Scala versions.

**Comment by iirekm** [comment] 2023-07-27 14:08
PySpark version: pyspark 3.4.1 (older seem to be no better)

**Comment by masseyke** [comment] 2023-07-27 14:27
Hi @iirekm. Can you post steps to reproduce this? Many people (myself included) have used es-hadoop with pyspark. If you want to start with a working example to maybe see what's wrong with your setup, check out https://github.com/masseyke/es-spark-docker. That's a docker container that is set up to run es-hadoop on a simple pyspark out of the box.

**Comment by masseyke** [comment] 2023-07-27 14:29
Also, you might try posting on https://discuss.elastic.co -- you're more likely to get support from the broader community there.

**Comment by masseyke** [comment] 2023-07-31 21:37
Hi @iirekm. I'm going to close this out since we don't have a confirmed es-hadoop issue. But please do post on https://discuss.elastic.co/ if you'd like advice for getting started. And feel free to reopen this (with steps to reproduce) if you confirm that there is a bug.

**Closed by masseyke** 2023-07-31 21:37 UTC
